/* Authored teaching examples. Public evidence is supplied separately by evidence.js. */
(() => {
  const p = text => `<p>${text}</p>`;
  const table = (heads, rows) => `<div class="table-scroll"><table><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const list = items => `<ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
  const model = text => `<div class="model"><p class="kicker">Worked response</p>${text}</div>`;
  const why = text => `<aside class="annotation"><strong>Why this is stronger</strong>${p(text)}</aside>`;
  const fiction = `<p class="fiction"><strong>Fictional teaching extension.</strong> The local records, people, quotations, meetings, and implementation results below are invented for instruction. They are not findings about Jordan High. Public charts retain their real school identity; the fictional setting is called Harbor High.</p>`;
  const section = (title,html) => ({title,html});
  const guide = (cycle,page) => `<a href="sources/CalAPA_C${cycle}_AssessmentGuide.pdf#page=${page}" target="_blank" rel="noreferrer">Cycle ${cycle} guide, Version 09</a>`;
  const chart = id => `<div data-chart="${id}"></div>`;
  const transcript = (title, rows, commentary) => `<h3>${title}</h3><p class="clip-header">Fictional transcript excerpts. Times are illustrative clip-relative anchors.</p><ol class="transcript">${rows.map(([time,speaker,text])=>`<li><time>${time}</time><p><strong>${speaker}</strong><br>${text}</p></li>`).join('')}</ol>${model(p(commentary))}`;
  const evidence = (items,question) => ({items,question});
  const dropout = `<a href="https://ies.ed.gov/ncee/wwc/PracticeGuide/24/Published" target="_blank" rel="noreferrer">WWC, Preventing Dropout in Secondary Schools (2017)</a>`;
  const writing = `<a href="https://ies.ed.gov/ncee/wwc/Docs/PracticeGuide/wwc_secondary_writing_110116.pdf" target="_blank" rel="noreferrer">WWC, Teaching Secondary Students to Write Effectively (2016)</a>`;
  const cstp = `<a href="https://docs.ctc.ca.gov/Document/Download/30328" target="_blank" rel="noreferrer">2024 California Standards for the Teaching Profession</a>`;
  window.COURSE = {
    areas: [
      {id:'start',title:'Getting Started',icon:'compass',description:'Understand the assessment and learn to read the Equity Gap app.'},
      {id:'c1',title:'Cycle 1',icon:'chart-no-axes-combined',description:'Investigate an equity gap, develop a response, and learn from feedback.'},
      {id:'c2',title:'Cycle 2',icon:'users',description:'Lead a community of practice from a shared problem to implementation.'},
      {id:'c3',title:'Cycle 3',icon:'messages-square',description:'Coach a teacher through observation, evidence, and a learning conversation.'}
    ],
    units: [
      {
        id:'orientation',area:'start',title:'What CalAPA asks you to demonstrate',focus:'Make the leadership reasoning visible.',rubrics:'All three cycles',parts:'Overview',guide:[1,5],
        lecture:[
          section('A performance assessment of leadership',p('CalAPA asks you to show how you investigate a need, make decisions with people, act on evidence, and examine your own leadership. A strong response gives the reader a traceable account: what you noticed, how you investigated it, what you decided, why you decided it, and what evidence changed your thinking. Clear prose matters because it makes that account inspectable.')+p('The repeated steps are Investigate, Plan, Act, and Reflect. The work differs across the cycles. Cycle 1 develops and revises strategies for an equity concern. Cycle 2 actually implements a strategy through a community of practice. Cycle 3 actually conducts an individual coaching cycle. A polished plan cannot stand in for implementation or observation when those are required.')),
          section('Three different kinds of leadership evidence',table(['Cycle','Central leadership work','What the reader needs to see'],[
            ['1: School improvement','Analyze data, examine contributing conditions, develop strategies, use feedback.','A defensible connection from a student-group equity gap to a revised improvement proposal.'],
            ['2: Community of practice','Facilitate collaborative inquiry and implementation over several weeks.','Adults analyzing implementation evidence, considering different views, and deciding next steps together.'],
            ['3: Teacher growth','Listen, agree on a focus, observe, analyze work, and coach.','A specific instructional conversation grounded in the teacher\'s goals, CSTP elements, lesson video, and student work.']
          ])),
          section('What makes an exemplary response',p('Precision is more useful than praise. Instead of saying that a meeting was inclusive, identify the facilitation move, show how another person responded, and explain how that response affected the decision. Instead of saying a strategy worked, specify the outcome, population, period, measure, and limit of the evidence.')+p('Use the official rubric to examine the quality of the reasoning, not as a list of impressive words to insert. These models demonstrate strong reasoning and revision; they are not assessor-scored exemplars or a promise of a particular score.'))
        ],
        walkthrough:[
          section('The case we will follow',p('Jordan High in Los Angeles Unified is the public-data starting point. Its 2025 reported graduation rate is 85.9% schoolwide and 70.8% for English Learners. Those results raise a question about equitable pathways to graduation. They do not tell us what caused the difference.')+chart('graduation-gaps')+fiction+p('In Harbor High, the fictional extension, a candidate investigates how English learners access feedback, revision opportunities, and credit support. A group of educators then studies a classroom writing routine. Finally, one volunteer teacher examines how feedback helps students explain their reasoning. The connection is instructional, not a claim that a classroom routine caused or solved Jordan\'s graduation gap.')),
          section('See the difference between reporting and analyzing',table(['Thin response','Stronger response','What changed'],[
            ['The data show English learners need help.','The reported 2025 graduation result for English Learners is 15.1 percentage points below schoolwide. I would investigate course-completion pathways and access to support before selecting a response.','Names a measure and comparison, then identifies what remains unknown.'],
            ['I encouraged everyone to participate.','After two colleagues interpreted the work differently, I asked each to identify the sentence supporting their judgment. Their comparison led us to revise the scoring descriptor.','Connects a leadership move to observable group learning.'],
            ['The teacher needs better differentiation.','At lesson 08:20, the teacher modeled a claim and evidence, but not the reasoning connecting them. Work A repeated the evidence without explaining it. We identified that missing connection as the next teaching focus.','Uses an event and a work sample instead of a global judgment.']
          ])),
          section('Use examples to learn the reasoning',p('Study the explanation and the annotations, then construct an account from your own setting and actions. The public-data examples are identified for verification. Fictional evidence is labeled where it appears. Actual submitted meetings and observations must be authentic; the invented transcripts illustrate what an evidence-rich interaction can reveal.'))
        ],
        evidence:evidence(['Distinguish the leadership work in each cycle.','Explain the difference between a reported outcome, an interpretation, and a causal claim.','Locate the Version 09 guide and submission specifications for your cycle.'],'Which leadership decision in your setting needs better evidence?')
      },
      {
        id:'gap-app',area:'start',title:'Read the Equity Gap app',focus:'Move from a chart to a defensible inquiry question.',rubrics:'Preparation for Cycle 1',parts:'Public evidence',guide:[1,10],
        lecture:[
          section('Select the right school and reporting period',p('Open the Equity Gap app and choose Select School. Search for Jordan High or CDS 19647331934454; confirm Los Angeles Unified and Los Angeles County. A matching school name alone is insufficient. Open Full Report for the overview, All Indicators for detail, and Equity Timeline Explorer for historical subgroup evidence. The app\'s CalAPA Cycle 1 Support page helps connect those findings to evidence you still need.')+p('Read the source year attached to each result. A report can contain different years for graduation, assessments, attendance, and English learner context. In this course, the saved public evidence is a local snapshot prepared on October 6, 2026; the worked graduation analysis uses reporting years 2023-2025.')),
          section('Read three views before choosing a focus',table(['View','Question','Example'],[
            ['Trend','How does the reported pattern vary across available years?','Schoolwide graduation rises from 78.1% in 2023 to 85.9% in 2025. Check historical definitions before treating the change as like-for-like.'],
            ['System comparison','What does the same-year comparison add?','In 2025, schoolwide graduation is 85.9%, district 86.5%, and state 87.8%. These are context, not matched comparison groups.'],
            ['Subgroup gap','Whose experience might an average conceal?','The 2025 English Learners result is 15.1 percentage points below schoolwide. Schoolwide includes that subgroup; it is not a separate control group.']
          ])),
          section('Read the measure before the color',p('A percentage-point gap is one rate minus another: 70.8 minus 85.9 equals -15.1. It is not a count of students or a percent decrease. In graduation, lower is concerning; in absenteeism, higher is concerning. Groups can overlap, and separate subgroup rows do not reveal the intersection of those groups.')+p('DataQuest high-school absenteeism is useful context, but the Dashboard Chronic Absenteeism Indicator covers TK-8. Smarter Balanced percent meeting or exceeding standard is different from Dashboard Distance from Standard. Graduation accountability denominators also have source-year definitions; recent combined four-/five-year measures are not simple four-year-only cohort rates. Keep those distinctions visible.'))
        ],
        walkthrough:[
          section('1. Start with the full graduation pattern',chart('graduation-trend')+model(p('The public file reports schoolwide graduation of 78.1%, 81.2%, and 85.9% in 2023, 2024, and 2025. This is an increase in the reported values. I would inspect the source-year definitions, especially the historical graduation measure and any DASS variant, before characterizing the size of a comparable improvement.'))),
          section('2. Add the same-year comparison',chart('graduation-comparison')+model(p('The schoolwide 2025 rate is 0.6 percentage points below the district rate and 1.9 points below the state rate. Those small system differences do not eliminate the need to examine within-school differences. Neither the district nor the state is a matched comparison group for estimating the school\'s effect.'))),
          section('3. Inspect the subgroup and denominator',chart('graduation-gaps')+model(p('The English Learners row reports 46 graduates and an accountability denominator of 65, producing the source-reported 70.8%. The schoolwide row reports 170 graduates with a denominator of 198, or 85.9%. The -15.1-point gap makes access to graduation pathways a defensible preliminary inquiry. English learner status is a reporting category, not an explanation of the outcome.'))+why('The interpretation identifies the source population, gives both denominators, and makes the next evidence decision explicit. It does not turn the largest bar into an automatic diagnosis.')),
          section('4. Preserve the evidence trail',p('In the gap app, inspect Data Sources and Verification and the detailed tables. Save the report and relevant tables with the year and measure notes. In Equity Timeline Explorer, choose Graduation, the English Learners group, and the relevant years. The saved three-year English learner table is available below; the default timeline export in the source packet selected African American / Black, which is a different group.')+`<p><a href="sources/graduation_el_history.csv" download>Download the English Learners history</a> &middot; <a href="sources/010_full_report_jordan_high.txt" download>Download the saved report text</a></p>`+p('Before using this as your own assessment evidence, refresh the most recent required years, confirm the same school and population, and retain the source definitions. The app provides public evidence; your qualitative investigation, leadership actions, and reflection come from your own work.'))
        ],
        evidence:evidence(['Confirm school, district, CDS, source year, and measure.','Inspect trend, system comparison, and subgroup evidence.','Retain counts, denominators, source files, and historical qualifications.','Explain what local evidence the chart cannot supply.'],'Write one descriptive claim and one question the chart cannot answer.')
      },
      {
        id:'c1-investigate',area:'c1',title:'Investigate: build the equity-gap analysis',focus:'Combine three years of quantitative evidence with at least three qualitative sources.',rubrics:'1.1, 1.2, 1.3',parts:'Part A',guide:[1,10],
        lecture:[
          section('Choose a state indicator and a specific group',p('Cycle 1 begins with one of the six state indicators and related quantitative evidence from the three most recent years. Identify one student group and explain why that choice is meaningful. A single current-year chart is an entry point, not the completed analysis. If the required three years cannot be accessed, the guide directs you to choose another indicator.')+p('For this example, Graduation Rate is the selected indicator and English Learners is the selected student group. Attendance and classroom work may inform the investigation, but they do not silently replace the indicator. Connect the concern to the school\'s actual vision, mission, or goals.')),
          section('Qualitative evidence must change the analysis',p('Collect at least three different qualitative sources that can illuminate the selected concern. Specify whose perspective each source represents, how it was collected, how you analyzed it, and what it adds. Three quotations copied from one interview are not three different sources. Look for disagreements and counterexamples as well as recurring themes.')+p('A useful analysis compares explanations across student accounts, observations, and documents. If learners describe feedback as unclear, examine what the written feedback says and observe how learners use it. A teacher\'s intention and a student\'s experience can both be honestly reported and still differ.')),
          section('Write the claim at the strength of the evidence',p('Describe patterns before naming possible contributing conditions. Do not infer that a racial identity, language status, family commitment, or teacher quality caused an outcome. Research can make an explanation plausible; it cannot verify that the explanation occurred locally. A strong Part A keeps findings, interpretation, and remaining questions distinguishable.'))
        ],
        walkthrough:[
          section('The public quantitative record',`<div data-history-table></div>`+model(p('Across the saved 2023-2025 records, the English Learners graduation rate is below schoolwide in every reported year: 69.2% versus 78.1%, 66.0% versus 81.2%, and 70.8% versus 85.9%. The descriptive gaps are -8.9, -15.2, and -15.1 percentage points. English Learners denominators vary from 52 to 47 to 65. These are annual accountability groups, not repeated observations of the same students. I can describe the recurring within-year disparity while reserving a claim about comparable change until historical definitions are reconciled.'))+chart('graduation-gaps')),
          section('Three local sources that deepen the inquiry',fiction+table(['Fictional source','How it was examined','Finding and counterexample'],[
            ['Q1: Student listening session, six volunteer English learners, Oct. 8','Open questions about a recent assignment, feedback, and an attempt to get help; compare experiences rather than count mentions as prevalence.','Four accounts describe unclear revision directions. Two describe useful conferences during class, showing that support is not uniformly inaccessible.'],
            ['Q2: Two observations of feedback and revision periods, Oct. 9-10','Record task directions, actual feedback language, requests for clarification, and whether students could use the feedback in class.','One class provides a worked explanation and revision time. The other returns scored work without a scheduled revision opportunity.'],
            ['Q3: Document analysis of six assignment/feedback packets and the support referral procedure, Oct. 11','Compare stated criteria, feedback specificity, revision deadlines, and the steps required to access support.','Three packets name a score but no specific next step. The referral procedure does not identify who checks whether a referral became an accessible appointment.']
          ])+model(p('The sources converge on a possible access problem: students may receive a score or referral without a usable next step. They also complicate it. Two student accounts and one observed class describe effective support during the school day. I therefore narrow the inquiry to variation in feedback and follow-through, rather than claiming that English learners lack motivation or that all teachers provide inadequate support. The fictional school goal is equitable completion of a rigorous graduation pathway; I would replace this illustrative goal with the verified site language in an actual submission.'))),
          section('What makes Part A persuasive',why('The quantitative table documents the disparity; the qualitative table examines possible conditions; the analysis explains convergence and disagreement. Each source does a different job. The response also names the limit: this small purposive investigation does not estimate how common these experiences are across the school.')+p('Part A allows up to five pages of responses, excluding the quantitative and qualitative data tables. Use the supplied template rather than expanding or deleting its prompts. See '+guide(1,28)+'.'))
        ],
        evidence:evidence(['One selected state indicator and student group.','Three most recent years, with denominators and source qualifications.','At least three different qualitative sources, analyzed and compared.','A connection to the verified school vision, mission, or goals.'],'Where do your qualitative sources agree, and where do they challenge your initial interpretation?')
      },
      {
        id:'c1-plan',area:'c1',title:'Plan: explain contributing conditions',focus:'Turn an outcome concern into a focused, feasible problem statement.',rubrics:'1.4, 1.5',parts:'Part B',guide:[1,17],
        lecture:[
          section('An outcome gap does not identify its cause',p('A graduation gap describes an outcome. A contributing condition concerns the opportunities, practices, structures, or decisions through which students encounter school. Examine adult-controlled conditions and alternatives. Separate a lack of access, a scheduling constraint, and a need for instructional learning; they call for different responses.')+p('Move through four questions: What condition is suggested? What local evidence supports it? What evidence complicates it? Which part can leaders feasibly influence? The purpose is a bounded problem of practice, not a sweeping indictment of the school.')),
          section('Use research to test the logic',p('A research connection should explain why a proposed mechanism deserves examination. The '+dropout+' discusses progress monitoring and individualized support. It gives a reason to inspect how the school identifies and responds to students who are off track. It does not establish that a specific local referral process caused the graduation difference.')+p('Record the research source, relevant recommendation or finding, population and setting, limitation, and local implication. Read the relevant evidence and its strength; a practice-guide recommendation is not a guarantee of an effect in this school.')),
          section('A problem statement should guide a decision',p('Name the student group, educational need, local condition supported by evidence, and feasible scope of change. Avoid putting a preferred commercial program or a promised outcome into the problem statement. The analysis should leave room for multiple responses and for feedback to change the plan.'))
        ],
        walkthrough:[
          section('Compare plausible contributing conditions',fiction+table(['Possible condition','Supporting fictional evidence','What remains uncertain'],[
            ['Feedback does not consistently identify a usable revision step.','Q1 learner accounts; three Q3 packets contain scores without a concrete next step.','Whether this pattern occurs in other courses or time periods.'],
            ['Access depends on students navigating support outside class.','Q2 contrast in protected revision time; Q3 unclear follow-through responsibility.','Other barriers, including scheduling or availability, require direct checks.'],
            ['Students have not learned the expected explanatory reasoning.','Q1 descriptions of knowing an answer but not how to explain it.','A comparable task and work review are needed; language proficiency alone cannot establish this.']
          ])),
          section('Worked Part B response',model(p('The public graduation evidence identifies a recurring English Learners disparity. In the fictional local investigation, the strongest actionable concern is inconsistent access to specific feedback and an opportunity to use it. Student accounts, observed revision periods, and assignment packets converge on that concern, while successful in-class conferences provide a counterexample. These findings point to a practice that can be examined and expanded, not a fixed characteristic of students.')+p('The school also lacks an explicit check that a support referral results in a feasible next step. The WWC dropout guide supports examining monitoring and individualized response as parts of a completion pathway. I use this research to frame the local question, not to claim that the observed referral process explains the entire graduation gap.')+p('<strong>Problem statement:</strong> In the fictional Harbor High inquiry, English learners in the reviewed credit-bearing courses do not consistently receive a specific revision direction and an accessible opportunity to act on it. The school needs a shared process for making feedback usable during instruction and checking that students can access follow-up support. The proposed scope is the participating courses and their support process; it does not encompass every source of the graduation disparity.'))+why('The statement locates an educational need in a modifiable school process. It names supporting evidence, retains a counterexample, uses research for reasoning, and limits the scope.')),
          section('Revision to avoid',table(['Overreach','More defensible revision'],[
            ['English learners graduate less often because families do not value school.','The public data do not measure family values. Investigate how students and families experience information and access to support.'],
            ['Tutoring will close the graduation gap.','Compare feasible responses to the identified access problem, then specify how their implementation and effects would be examined.']
          ]))
        ],
        evidence:evidence(['Distinguish the outcome gap from a contributing condition.','Support institutional or structural conditions with local evidence and research.','Consider contradictory evidence and alternative explanations.','Write a problem statement within a feasible leadership scope.'],'What would make you revise your preferred explanation?')
      },
      {
        id:'c1-act',area:'c1',title:'Act: develop and revise the strategy',focus:'Show how feedback changes the proposal and its implementation conditions.',rubrics:'1.6, 1.7',parts:'Part C',guide:[1,21],
        lecture:[
          section('Make every strategy answer a condition',p('For each proposed strategy, identify the condition it addresses, the responsible adults, resources, timing, student access, and the evidence that would show whether it is being implemented. A list of desirable activities is weaker than a small set of connected actions with a clear rationale.')+p('In Cycle 1, the action includes seeking informed feedback and revising the strategies. Do not invent implementation results to make the proposal look complete. Distinguish a planned measure from a result you actually observed.')),
          section('Feedback should leave a trace',p('Explain why the administrator or educational leader you approached knows the school culture and can test the proposal. Document the substance of feedback, the change you made, and its implications for time, access, staffing, and buy-in. Agreement is not the only useful feedback; a concern can improve the plan.')+p('Build support by involving affected people in decisions they can influence. Explain how students, families, and educators can question the proposal and how their feedback will be used. A signature or attendance list alone does not demonstrate buy-in.'))
        ],
        walkthrough:[
          section('The initial proposal and its revision',fiction+table(['Initial proposal','Fictional feedback','Revised decision'],[
            ['Offer revision help after school twice weekly.','The instructional leader asks how students with transportation or care responsibilities will attend. Q1 already includes an example of useful help during class.','Schedule an in-class model, feedback, and revision routine; retain additional help without making it the only route.'],
            ['Teachers refer students to a counselor if credits are at risk.','The counselor asks who follows up and how the student knows what happened.','Name a staff contact, document the student\'s next step, and check access within one school week.'],
            ['Judge success by the next graduation rate.','The leader notes that the annual rate is too distant and the cohort will change.','Track implementation and near-term student work first; review completion outcomes later without attributing change to the pilot alone.']
          ])),
          section('Worked Part C response',model(p('I proposed a common classroom routine in which students examine an explanation, draft a response, receive one actionable next step, and revise during protected class time. This addresses the fictional evidence of unclear feedback and uneven revision access. A parallel referral check gives each student a named adult contact and an understandable next step when course completion is at risk.')+p('I sought feedback from the instructional leader because she controls the professional-learning calendar and understands the participating departments\' schedules. Her access question exposed a contradiction: my after-school-only proposal could reproduce the barrier identified in the listening session. I moved the core opportunity into instruction and asked the counselor to review the feasibility of the follow-through process.')+p('The revised proposal begins with a six-week pilot in participating courses. Teachers would retain the original and revised work, note whether the routine occurred, and ask students whether they could understand and use the feedback. The instructional leader would protect two common planning periods; the counselor would check referral completion weekly. The pilot would examine feasibility and learning evidence. It would not establish an effect on graduation.'))),
          section('A monitoring plan that matches the proposal',table(['Question','Proposed evidence','Decision rule for discussion'],[
            ['Did the opportunity occur?','Weekly implementation log and sampled assignment directions.','If the routine is skipped, address feasibility before interpreting work outcomes.'],
            ['Could students use the feedback?','Original/revised work plus a brief student explanation of the next step.','If work remains unchanged, distinguish unclear feedback from lack of time or instructional understanding.'],
            ['Did a referral lead to accessible support?','Referral follow-through record and student confirmation.','An uncompleted handoff triggers a named adult follow-up, not blame assigned to the student.']
          ])+why('The response shows an actual revision in the fictional case, explains who influenced it, and links monitoring to decisions. It avoids treating a future graduation target as current evidence of success.'))
        ],
        evidence:evidence(['Strategies connect to the problem statement and contributing conditions.','Feedback-provider selection is justified.','Feedback, revision, and implications are documented.','Buy-in and monitoring steps have owners and feasible timing.'],'Which part of your proposal changed because someone challenged it?')
      },
      {
        id:'c1-reflect',area:'c1',title:'Reflect: examine your leadership learning',focus:'Explain how evidence and feedback changed your judgment.',rubrics:'1.8',parts:'Part D',guide:[1,24],
        lecture:[
          section('Reflection is an argument about your learning',p('Name a consequential decision, explain your initial reasoning, identify evidence or feedback that challenged it, and show what changed. Use the earlier parts as evidence. A chronology of tasks completed does not explain leadership learning.')+p('Include both a strength and a growth need. Make the next professional-learning goal observable: what will you practice, when, with whom, and what evidence will help you assess your improvement? A generic promise to communicate better is difficult to evaluate.')),
          section('Check the whole cycle for consistency',p('The group and outcome selected in Part A should remain visible in the problem statement, strategy, and reflection. If you changed the focus, explain why and reconcile all parts. Keep a distinction between the public outcome evidence, local findings, proposed actions, and actual feedback.')+p('For Version 09, Part D can be a written reflection up to five pages or a video explanation up to five minutes. This option differs from the recorded meeting evidence in later cycles. '+guide(1,29)+'.'))
        ],
        walkthrough:[
          section('Worked Part D response',fiction+model(p('I initially interpreted the graduation disparity as a reason to expand tutoring. The qualitative comparison changed that interpretation: some learners already accessed effective help, while others received feedback or a referral without a usable next step. My first proposal increased the amount of help without asking who could use it. The instructional leader\'s question about access led me to revise the core opportunity into the school day.')+p('A strength was my willingness to examine the counterexamples in Q1 and Q2 instead of forcing every source to confirm my initial explanation. A limitation was that I sought student perspectives during investigation but did not initially include students in reviewing the proposal. Before piloting it, I would ask a small student advisory group to examine the directions and access arrangements and record the changes prompted by their feedback.')+p('My professional-learning goal is to become more systematic in translating evidence into feasible access decisions. During the next six weeks, I will use a decision log in two planning meetings: evidence considered, alternative considered, whose perspective is missing, and reason for the choice. I will ask a mentor to review whether the log reveals genuine changes in my thinking. This cycle strengthened the proposal; it did not demonstrate improved graduation outcomes.'))+why('The reflection makes a specific limitation visible and turns it into a testable growth activity. It references earlier evidence instead of introducing an unsupported success story.')),
          section('A short video-reflection alternative',p('For an illustrative four-minute reflection, begin with the original interpretation, move to the qualitative counterexample and feedback, explain the revised strategy, and close with the professional-learning goal. Use evidence references rather than reading a list of accomplishments. The actual candidate would explain their own work in their own voice.')),
          section('The complete Cycle 1 evidence sequence',table(['Part','What it establishes','Version 09 written limit'],[
            ['A','Quantitative and qualitative analysis, selected group, equity gap and school-goal connection.','5 pages of responses; data tables excluded.'],
            ['B','Contributing conditions, research connection, and feasible problem statement.','5 pages.'],
            ['C','Strategies, feedback, revisions, buy-in, and implications.','5 pages.'],
            ['D','Evidence-based reflection and professional growth.','5 pages, or a video up to 5 minutes.']
          ]))
        ],
        evidence:evidence(['Reflection cites decisions and evidence from Parts A-C.','Strengths and growth needs are specific.','Professional learning has an action, timeframe, and way to examine progress.','All parts use a consistent indicator, group, and problem.'],'What did you learn that you could not have written before doing the cycle?')
      }
    ]
  };
  window.COURSE_HELPERS = {p,table,list,model,why,fiction,section,guide,chart,transcript,evidence,dropout,writing,cstp};
})();

(() => {
  const {p,table,list,model,why,fiction,section,guide,chart,transcript,evidence,dropout,writing,cstp} = window.COURSE_HELPERS;
  window.COURSE.units.push(
    {
      id:'c2-investigate',area:'c2',title:'Investigate: form a community of practice',focus:'Choose an educational focus and people positioned to learn and act together.',rubrics:'2.1, 2.2',parts:'Part A',guide:[2,11],
      lecture:[
        section('Begin with the existing professional-learning culture',p('Investigate how educators currently learn together. Examine the purposes of meetings, whose knowledge counts, how student evidence enters the discussion, and whether decisions lead to follow-through. Explain the implications for your facilitation. A schedule of existing meetings is context; analysis shows what the schedule and practices enable or constrain.')+p('Select three to five educators or educational partners in addition to yourself. Choose members because their experience and responsibilities fit the educational focus. Explain their different contributions and the conditions needed for honest participation.')),
        section('Public data set the context; local work defines the focus',p('The graduation pattern can motivate attention to equitable course completion. It cannot tell a community which classroom practice to select. Bring relevant student work and local evidence into the planning conversation. The community jointly identifies a problem of practice and selects one evidence-based strategy.')+p('Cycle 2 includes an initial planning meeting and at least three additional implementation meetings over several weeks. The planning meeting does not count as one of the three implementation meetings. Plan enough time for educators to try the strategy and bring evidence back.'))
      ],
      walkthrough:[
        section('Worked Part A response',fiction+model(p('At fictional Harbor High, department meetings are scheduled twice monthly, but the reviewed agendas are dominated by announcements and pacing. Teachers describe informal exchanges of materials; there is no consistent routine for examining student work across classrooms. This creates an opportunity for collaborative inquiry but also a risk that the new group becomes another information meeting.')+p('The educational focus is English learners\' access to feedback and revision in credit-bearing courses, aligned with the fictional school\'s equitable-completion goal. The public graduation pattern explains why the concern matters; the local Q1-Q3 evidence identifies a feasible instructional question. I invited an English teacher, a mathematics teacher, an English language development specialist, and a counselor. The teachers contribute classroom implementation evidence, the specialist examines language demands, and the counselor connects classroom opportunities to course-completion support. I facilitate as a fifth participant.')+p('Because colleagues have different status and expertise, I will use independent review before discussion, ask members to ground interpretations in work, and record competing explanations before seeking a decision. I will ask for feedback after each meeting about whose ideas influenced the plan. These arrangements respond to the observed meeting culture; they do not guarantee equitable participation.'))),
        section('Membership with a reason',table(['Fictional member','Contribution','Question that member can challenge'],[
          ['English teacher','Writing tasks, criteria, feedback and revision.','Does the routine make the reasoning demand clear?'],
          ['Mathematics teacher','Explanations of solutions and classroom feasibility.','Does the approach transfer beyond an English assignment?'],
          ['ELD specialist','Language development and access to grade-level thinking.','Are we confusing language features with the quality of reasoning?'],
          ['Counselor','Credit pathways, support access, follow-through.','Can learners actually use the opportunities we offer?']
        ])+why('The group is justified by the problem and the knowledge needed. The candidate also analyzes the existing learning culture instead of merely announcing a new team.'))
      ],
      evidence:evidence(['Analysis of current professional-learning practices and implications.','A student-evidence-based focus connected to site goals.','Three to five educators or partners besides the candidate, with justified roles.','Time for a planning meeting and at least three implementation meetings.'],'Which member could reveal a weakness in your preferred solution?')
    },
    {
      id:'c2-plan',area:'c2',title:'Plan: choose the problem and strategy together',focus:'Make joint reasoning visible in the agenda, minutes, and narrative.',rubrics:'2.3, 2.4',parts:'Parts B, C, D',guide:[2,17],
      lecture:[
        section('An agenda is a plan; minutes document what occurred',p('The agenda should reserve time for the group to examine student evidence, distinguish interpretations, agree on a problem, consider a relevant evidence-based strategy, and plan implementation. Minutes should capture the evidence considered, differences in interpretation, decisions, rationale, owners, and next steps. They should not simply repeat the agenda in past tense.')+p('The provided B and C templates are optional formats; the planning agenda and minutes are required evidence. The guide says the planning meeting should not be recorded and does not count toward the three implementation meetings.')),
        section('Select one strategy with a coherent mechanism',p('In the teaching case, the group adapts a model-practice-reflect writing routine with feedback informed by student work. Its proposed mechanism is specific: make the reasoning move visible, let students practice it, and provide time to inspect and revise it. The '+writing+' is the research anchor. The cross-subject adaptation needs local testing; the research does not prove that this particular adaptation improves graduation.')+p('Describe how the group reached its choice. Consensus means a reasoned shared decision, not the absence of questions or the facilitator announcing a solution before discussion.'))
      ],
      walkthrough:[
        section('Fictional planning agenda and minutes',fiction+table(['Time','Agenda: intended work','Minutes: what happened'],[
          ['0-8 min','Review focus and anonymous work samples.','Members separate missing reasoning from language conventions. Two samples show correct answers with no explanation.'],
          ['8-20 min','Compare interpretations and formulate a problem.','The ELD specialist challenges the phrase "weak English." The group revises the focus to the missing connection between evidence and claim.'],
          ['20-32 min','Examine the writing practice guide and compare responses.','The group considers after-school help, more written comments, and explicit modeling with revision. It selects the in-class routine because the local evidence concerns usable feedback and access.'],
          ['32-45 min','Agree on a common routine and evidence.','Teachers will model a reasoning connection, collect a first attempt, give one next-step prompt, and allow revision. Each brings six matched pairs, including varied performance, plus an implementation log.']
        ])),
        section('Worked Part D response',model(p('The community agreed that students in the reviewed work could often state a claim or answer but did not consistently explain how the evidence justified it. We examined whether this reflected the task, the model, feedback, or opportunity to revise. The ELD specialist\'s challenge prevented us from treating language status as a diagnosis. We reframed the problem around the instructional opportunity to learn and revise explanatory reasoning.')+p('We jointly selected a model-practice-reflect routine informed by the WWC secondary writing guide. Each teacher would model the reasoning connection, ask students to apply it, offer one actionable feedback prompt, and protect revision time. The English teacher favored more comments; the mathematics teacher questioned the time required. Comparing the work and Q1 accounts helped the group favor a small, teachable routine over a larger comment load. Both teachers agreed to trial it, with time feasibility explicitly monitored.')+p('We will examine six matched work pairs per teacher, selected to include a range of first-attempt quality rather than only successes. A common descriptor will distinguish a claim, relevant evidence, and an explanation connecting the two. These purposeful samples will support professional learning. They will not produce a schoolwide estimate of effectiveness.'))+why('The narrative shows how a disagreement changed the focus and how the group selected one strategy. It describes a proposed mechanism and an evidence plan without claiming results before implementation.')),
        section('The shared work product',table(['Reasoning descriptor','Evidence in student work'],[
          ['0: Connection absent','An answer or claim appears with no relevant supporting evidence.'],
          ['1: Evidence named','Relevant evidence appears, but the connection to the claim is not explained.'],
          ['2: Connection explained','The response explains why the evidence supports the claim.']
        ])+p('This fictional classroom descriptor is an instructional tool, not a CalAPA scoring scale. Keep the criterion consistent across matched drafts and discuss disagreements before summarizing the samples.'))
      ],
      evidence:evidence(['Planning agenda and actual minutes.','Joint selection of the problem and one evidence-based strategy.','Documented disagreement, reasoning, and decision.','A plan for implementation, work samples, and meeting evidence.'],'Where do the minutes show that someone other than the facilitator changed the decision?')
    },
    {
      id:'c2-act',area:'c2',title:'Act: facilitate implementation and record evidence',focus:'Show adults using evidence, examining differences, and deciding next steps.',rubrics:'2.5, 2.6',parts:'Parts E, F, G, H, I',guide:[2,23],
      lecture:[
        section('Implementation produces new evidence',p('Hold and record at least three implementation meetings. Between meetings, members use the selected strategy and bring work, implementation notes, or other evidence back. A repeated discussion of the original gap-app graph does not document implementation. The public graph explains the larger concern; new local evidence shows what the community is learning.')+p('Collect one file of implementation agendas, one of minutes, and one of key collaborative work products. Select three clips, each up to five minutes: purpose and data review; professional collaboration; results and next steps. The eight-page written or ten-minute video commentary explains what you did, why, and the observed response at specific clip times.')),
        section('Set up a recording that makes the interaction visible',p('Use a stable camera facing the candidate and actively participating members around the table, with light on faces and a microphone that captures quiet speakers. Place an anonymous work sample within view or refer to a clearly labeled copy. Test sound with people in their actual seats. Obtain required permissions and record the authentic meetings; do not assign lines, speakers, or reactions from the example transcript.')+p('Capture the whole meeting, then choose evidence-rich excerpts. Keep each clip within its limit. The guide permits minimal editing to demonstrate the constructs; the excerpt must still represent what happened. Do not upload assessment meeting videos to public platforms.')),
        section('Commentary should analyze a visible moment',p('Anchor the commentary to a brief, precise range. Explain the interpretation problem, the facilitation move, the participants\' response, and its consequence for the decision. A timestamp covering the entire clip does not identify the evidence. Do not claim that every member felt included merely because everyone spoke.'))
      ],
      walkthrough:[
        section('Three meetings with changing work products',fiction+table(['Meeting','Implementation evidence','Fictional decision recorded in minutes'],[
          ['1: Week 2','Twelve first-attempt/revised pairs; implementation notes.','Seven of twelve revised responses reach descriptor 2. Recheck the criterion because two pairs were scored differently. Keep the model, clarify the descriptor.'],
          ['2: Week 4','Six new matched pairs per teacher; examples of feedback wording.','Nine of twelve revised responses reach descriptor 2. Some prompts invite copying. Add a question requiring learners to justify a new example.'],
          ['3: Week 6','A third set of twelve pairs, student explanations, teacher feasibility notes.','Eight of twelve revised responses reach descriptor 2. Retain revision time, revise the model, and sample another task before expanding.']
        ])+p('These are three different sets of purposeful samples, not a repeated-student experiment. The counts describe the fictional reviewed work. The drop from nine to eight matters: the group investigates task differences rather than reporting uninterrupted success.')),
        section('Clip 1: purpose and implementation-data review',transcript('Meeting 1: establish the question',[
          ['00:08','Candidate','Our question today is whether students used the feedback to connect evidence to a claim. The graduation graph explains why we began, but these work pairs show what happened during our first trial.'],
          ['00:38','English teacher','Seven revised responses meet our reasoning descriptor. I thought that meant we should extend the routine.'],
          ['01:02','Candidate','Before deciding, let us read pair B independently. What changed between the first and revised response?'],
          ['01:35','Mathematics teacher','The student added the number we requested, but I still cannot see why it supports the answer.'],
          ['02:00','ELD specialist','I scored that as evidence named, not connection explained. Our descriptor may be doing two jobs.'],
          ['02:25','Candidate','Let us mark the exact sentence each interpretation depends on. Then we can decide whether to revise the score, the descriptor, or the teaching.']
        ],'At Clip 1, 01:02-02:25, I paused a move toward expansion and asked the group to inspect pair B. Independent reading exposed disagreement about the criterion. The group shifted from celebrating a count to examining what the count represented. My next move was to record the disagreement and calibrate the descriptor before using the tally to justify expansion.')),
        section('Clip 2: professional collaboration',transcript('Meeting 2: work through disagreement',[
          ['00:05','Mathematics teacher','I cannot use ten minutes for revision in every lesson. We are already behind.'],
          ['00:28','Candidate','That is a feasibility concern we need to solve. Which part takes the time: the model, the feedback, or students beginning the revision?'],
          ['00:54','Mathematics teacher','They wait for me to tell them exactly what sentence to write.'],
          ['01:20','ELD specialist','The prompt names the answer. Could we ask what the number means in the situation instead?'],
          ['01:44','English teacher','That might help in my class too. The stronger samples explain the evidence in their own words.'],
          ['02:10','Candidate','We have two suggestions: shorten the opportunity, or change the prompt that creates the waiting. What evidence supports each?'],
          ['03:02','Counselor','Students described waiting for clarification in our earlier inquiry. Changing the prompt addresses that concern without removing the opportunity.'],
          ['03:35','Candidate','I hear agreement to retain revision time and test a prompt that asks for justification. Does anyone see a condition under which that would not be feasible?']
        ],'At Clip 2, 00:28-02:10, I treated the time concern as information rather than resistance. Asking which part consumed time brought an instructional issue into view. The specialist and English teacher then connected the concern to the feedback wording and work. At 03:35 I checked for remaining constraints instead of equating silence with agreement. The resulting decision retained access while changing the prompt.')),
        section('Clip 3: results and next steps',transcript('Meeting 3: interpret mixed results',[
          ['00:08','Candidate','Our latest reviewed set has eight of twelve revised responses at descriptor 2, compared with nine in the previous set. What can we explain, and what is still uncertain?'],
          ['00:35','English teacher','This task required two pieces of evidence. It may not be comparable to the previous task.'],
          ['01:00','Mathematics teacher','The model showed one example. Students who finished could repeat it, but some struggled with the new situation.'],
          ['01:30','Candidate','So the tally alone does not tell us that the routine weakened. Let us compare the task demands and the reasoning in two contrasting samples.'],
          ['02:20','ELD specialist','We should model choosing between explanations, not just completing a sentence.'],
          ['02:55','Candidate','What will we keep, what will we revise, and what evidence would help us decide whether to expand?'],
          ['03:20','English teacher','Keep in-class revision, add contrasting explanations to the model, and collect another set on a task with the same reasoning demand.'],
          ['03:50','Candidate','I will document those decisions. Each teacher brings six matched pairs and notes the time used; we will also ask students to explain how they used the prompt.']
        ],'At Clip 3, 00:08-01:30, I made the less favorable tally visible and asked the group to distinguish results from explanations. Members identified task differences and a possible limit of the model. At 02:55-03:50, I asked them to name retained and revised components and the next evidence. The decision supports another local inquiry; it does not demonstrate an effect on graduation or a statistically established intervention effect.'))
      ],
      evidence:evidence(['At least three implementation meetings, with agendas and minutes.','Key collaborative products, up to ten pages in one file.','Three labeled clips, each no longer than five minutes.','Commentary connects exact moments, facilitation rationale, response, and decisions.'],'Which moment shows that your facilitation changed how the group used evidence?')
    },
    {
      id:'c2-reflect',area:'c2',title:'Reflect: evaluate facilitation and group learning',focus:'Use implementation evidence and participant feedback to examine your leadership.',rubrics:'2.7',parts:'Part J',guide:[2,28],
      lecture:[
        section('Evaluate the learning process as well as the result',p('Consider how your facilitation helped the group reason, disagree productively, adjust practice, and interpret implementation evidence. Explain what participant feedback revealed that the video alone could not establish. Connect your growth goals to actual limitations in the cycle.')+p('Be precise about results. A purposeful work sample can inform a local instructional decision without establishing a causal effect. A meeting decision can show professional learning without proving classroom implementation. A promise to continue is not evidence that continuation occurred.')),
        section('Close the evidence chain',p('Reconcile the narrative, agendas, minutes, products, clips, commentary, and reflection. Each document should support the same chronology. Include all required parts: the absence of a blank G or H template in the ZIP does not mean that work products or video clips are optional. Part J allows up to four written pages or a video explanation up to five minutes.'))
      ],
      walkthrough:[
        section('Feedback that changes the next facilitation cycle',fiction+table(['Fictional feedback','Interpretation','Next practice'],[
          ['Teacher: "Independent reading helped me disagree without interrupting."','The protocol created an entry point for a different interpretation.','Retain independent inspection before discussion.'],
          ['Counselor: "I understood the tally only after the scoring discussion."','I assumed shared understanding too early.','Begin with one jointly examined example before presenting an aggregate.'],
          ['ELD specialist: "I was asked about language, but the decision was already narrowing."','Role-based invitations can limit someone\'s influence.','Invite all members to critique the problem and strategy before assigning expertise.']
        ])),
        section('Worked Part J response',model(p('Our initial implementation produced evidence of revision in some reviewed work, but the three sampled sets were not directly comparable and did not show uniform improvement. The most defensible group learning was greater precision about what counted as explanatory reasoning and how our prompts affected the opportunity to demonstrate it. The revised descriptor and the meeting 3 decision log make that learning visible.')+p('In Clip 2, 00:28-02:10, I helped the group investigate a feasibility concern instead of dismissing it. That was a facilitation strength. However, the ELD specialist\'s feedback showed that I sometimes invited expertise after the decision had begun to narrow. In the next cycle, every member will first identify a possible alternative interpretation and a design concern. I will ask a colleague to note whose suggestions enter the final decision log, and I will compare those notes with members\' own accounts.')+p('We agreed to retain in-class revision and test a model using contrasting explanations. Continued use still depends on protected meeting time and workable lesson integration. I would present the principal with the time requirement and mixed evidence, not only the strongest samples. The public graduation indicator remains the longer-term concern; this cycle does not establish an effect on that indicator.'))+why('The reflection uses participant feedback to challenge the candidate\'s self-assessment. It states a concrete improvement in facilitation and preserves the limits of the implementation results.')),
        section('All ten parts in one sequence',table(['Step','Required evidence','Format note'],[
          ['Investigate','A: context, educational focus, community of practice.','Up to 5 pages.'],
          ['Plan','B: planning agenda; C: minutes; D: problem and strategy narrative.','B/C format optional; artifacts required. D up to 4 pages.'],
          ['Act','E: implementation agendas; F: minutes; G: products; H: 3 clips; I: commentary.','G up to 10 pages. H up to 5 minutes each. I up to 8 pages or 10 minutes.'],
          ['Reflect','J: reflective narrative.','Up to 4 pages or 5 minutes.']
        ]))
      ],
      evidence:evidence(['Implementation claims match actual collected evidence.','Member feedback informs reflection and a growth goal.','All Parts A-J are accounted for, including G and H.','Video commentary and timestamps match the selected footage.'],'Which piece of member feedback challenged your view of your own facilitation?')
    },
    {
      id:'c3-investigate',area:'c3',title:'Investigate: understand the coaching context',focus:'Build a partnership with a volunteer teacher and examine existing practice.',rubrics:'3.1',parts:'Part A',guide:[3,11],
      lecture:[
        section('The schoolwide graph cannot evaluate a teacher',p('The Equity Gap app can help identify a broad concern. It cannot establish what happened in a particular classroom or determine a teacher\'s effectiveness. Cycle 3 requires classroom-specific evidence and a coaching partnership. The teacher\'s perspective, students\' assets, lesson goals, and actual work shape the focus.')+p('Investigate current coaching, observation, and instructional feedback practices at the site. Examine how standards guide the process, how evidence is collected, who sets goals, and what follow-up occurs. Explain the implications for your own cycle, especially if teachers associate observation with evaluation.')),
        section('Choose a volunteer and an appropriate focus',p('Describe the volunteer teacher\'s experience and prior coaching, the classroom and students, and why the partnership is appropriate. Agree on how evidence will be used. The teacher is a participant in choosing the observation focus, not the recipient of a diagnosis based on a public report.')+p('The model uses the 2024 CSTP, selecting elements 5A and 5B within the same standard, assessing students for learning. In your own setting, use the applicable framework and provide the required crosswalk if another framework is used. Read the precise elements with the teacher.'))
      ],
      walkthrough:[
        section('Worked Part A response',fiction+model(p('At fictional Harbor High, teachers receive a formal observation and written evaluation, while informal instructional coaching depends on individual requests. The sample observation form emphasizes teacher actions but gives limited space to analyze student work or revisit a goal. The volunteer teacher describes useful feedback on classroom routines but little opportunity to review evidence together afterward. I therefore plan a cycle in which the teacher helps set the question and examines the evidence with me.')+p('The volunteer is a fourth-year English teacher participating in the community of practice. Her Grade 10 class has 28 learners, including nine currently identified as English learners. Students bring knowledge of multiple languages, community experiences, and varied interests in the argument topic. These fictional classroom details are separate from the real graduation accountability group. The teacher wants to know whether students understand her feedback well enough to revise an explanation rather than merely add more words.')+p('We agree that this coaching cycle will focus on evidence for professional learning. We will review one lesson and its work products, distinguish observations from interpretations, and jointly select next steps. I will make the evidence collection visible in advance so the post-observation meeting is a learning conversation rather than a surprise judgment.'))+why('The response connects the site\'s existing practices and the teacher\'s experience to a specific coaching design. It does not infer a classroom deficit from the graduation chart.')),
        section('The coaching question',p('<strong>How does the teacher gather and use evidence of students\' explanatory reasoning during the lesson, and what do students do with the feedback?</strong> This question gives the observation a manageable focus. It does not require the coach to rate every dimension of instruction.'))
      ],
      evidence:evidence(['Analysis of existing coaching and feedback practices.','Volunteer teacher context, experience, and learning needs.','Student assets and classroom-specific evidence.','Implications for the coaching relationship and observation process.'],'What about the teacher\'s prior experience should change how you approach this conversation?')
    },
    {
      id:'c3-plan',area:'c3',title:'Plan: agree on the lesson and observation',focus:'Co-select CSTP elements and define the evidence before the lesson.',rubrics:'3.2',parts:'Parts B, C, D, E',guide:[3,16],
      lecture:[
        section('The pre-observation meeting is substantive evidence',p('Listen to the teacher\'s self-assessment, examine the lesson plan and student assets, agree on one or two CSTP elements from the same domain, and decide what evidence will be collected. A focus such as "student engagement" is too broad unless you define what you will actually observe.')+p('The lesson plan should identify the learning goal and the work product. The observation plan should identify the evidence: exact teacher prompts, student responses, the use of criteria, and changes between first and revised work. Distinguish the teacher\'s plan from evidence that the plan occurred.')),
        section('Video setup and required clips',p('Place the camera so the teacher and candidate remain visible and audible while reviewing the plan and sample work. Record the authentic pre-observation conversation. Select two clips, each up to six minutes: one showing teacher needs, lesson review, and CSTP selection; the second showing agreement about observation and evidence collection.')+p('Part B is the classroom/lesson narrative, Part C is the teacher\'s lesson plan, Part D contains the two clips, and Part E explains the coaching at specific moments. The commentary may be up to eight written pages or ten minutes of video.'))
      ],
      walkthrough:[
        section('Lesson and observation agreement',fiction+table(['Decision','Fictional agreement'],[
          ['Learning goal','Students justify a claim about a school policy with relevant evidence and an explanation of why the evidence supports the claim.'],
          ['Lesson sequence','Examine two explanations; teacher models a reasoning choice; students draft; teacher checks work and gives one next-step prompt; students revise and explain the revision.'],
          ['CSTP focus','2024 CSTP 5A and 5B: gather meaningful assessment evidence and use it to inform the next learning step. Both are within CSTP 5.'],
          ['Observable evidence','Record exact prompts, student responses, which evidence the teacher uses before adjusting instruction, and six varied matched work pairs.'],
          ['Student access','Allow oral rehearsal and appropriate language resources while retaining the reasoning demand; honor individual learning plans.'],
          ['Recording and review','Record a 30-minute observation, with required permissions; review the lesson recording and work before a recorded post-observation meeting.']
        ])+p('CSTP descriptions above are paraphrases; consult the '+cstp+' for the official wording.')),
        section('Pre-observation Clip 1',transcript('Teacher needs, lesson review, and CSTP selection',[
          ['00:10','Candidate','Which part of the recent student work is most useful for deciding what you want to learn from this lesson?'],
          ['00:32','Teacher','Students often add another quotation after feedback. They do not explain the one they already have.'],
          ['01:02','Candidate','Show me an example where that happened and one where the reasoning is visible. What do you notice?'],
          ['01:45','Teacher','In this stronger piece, the student explains why the detail matters. I want to know whether my prompt helps the others do that.'],
          ['02:20','Candidate','Would focusing on how you gather evidence and use it for the next teaching move fit that question? Let us read CSTP 5A and 5B together.'],
          ['03:10','Teacher','Yes. I want evidence of what I learn from the first attempt and how that changes my feedback, not just a count of who answers aloud.']
        ],'At Pre-observation Clip 1, 01:02-02:20, I asked the teacher to compare contrasting work before naming a focus. Her analysis identified the missing reasoning connection and led us to CSTP 5A and 5B. This gave the teacher a substantive role in choosing the focus rather than asking her to endorse a standard I had already selected.')),
        section('Pre-observation Clip 2',transcript('Observation process and evidence',[
          ['00:08','Candidate','What would you like the observation record to show when you look at a first attempt?'],
          ['00:28','Teacher','What I notice and what I ask the student to do next.'],
          ['00:58','Candidate','I can record your exact prompt, the response, and whether the revised work makes a new connection. We will include examples that do and do not improve.'],
          ['01:35','Teacher','Include a student who explains orally but writes very little. Otherwise we might miss what the student understands.'],
          ['02:00','Candidate','Agreed. Let us note the oral explanation separately from the written product. Which lesson segment should we replay together afterward?'],
          ['02:34','Teacher','The check of first drafts and the feedback. I would like to see whether I change my approach after looking at their work.']
        ],'At Pre-observation Clip 2, 00:58-02:00, we specified the record rather than assuming that "student understanding" was self-evident. The teacher\'s suggestion broadened the evidence to include an oral explanation, while keeping it distinct from written performance. That change respects a student asset and improves the validity of the coaching conversation.'))
      ],
      evidence:evidence(['Teacher self-assessment, lesson goals, and student assets discussed.','One or two jointly selected CSTP elements from the same domain.','Teacher lesson plan and specified student work product.','Two pre-observation clips, up to six minutes each, with anchored commentary.'],'What observation evidence did the teacher help you add or change?')
    },
    {
      id:'c3-act',area:'c3',title:'Act: observe, analyze, and coach',focus:'Connect lesson evidence, student work, and jointly chosen next steps.',rubrics:'3.3, 3.4, 3.5',parts:'Parts F, G, H, I',guide:[3,20],
      lecture:[
        section('Collect low-inference evidence',p('Observe at least twenty minutes and record the teacher\'s instruction for the full observation. Record what was said or done before interpreting its meaning. "The teacher asked three students to explain why" is an observation; "the teacher valued reasoning" is an interpretation that needs supporting evidence.')+p('Analyze the selected CSTP evidence and student work, and watch the lesson recording before the post-observation meeting. Select moments that help the teacher examine strengths and growth needs. Collect work that complicates the interpretation, not only the most successful example.')),
        section('Use the evidence in the conversation',p('Ask for the teacher\'s assessment of student learning, inspect the work together, replay relevant lesson video, and connect observations to the agreed CSTP elements. Listen for the teacher\'s explanation before offering yours. A useful coaching question opens analysis; it does not disguise a predetermined judgment.')+p('The teacher and candidate should agree on a next step, a resource or support, and evidence for follow-up. Part H permits one to three post-observation clips totaling no more than fifteen minutes; each clip should be at least one minute. Both participants must be visible and audible. Part I commentary is up to eight written pages or ten minutes of video.'))
      ],
      walkthrough:[
        section('Observation notes and student work',fiction+table(['Lesson time','Observed event','Interpretation to examine'],[
          ['05:40','Teacher highlights a claim and quotation in the model. No explanation of the connection is spoken in this segment.','The reasoning step may remain implicit. Check other segments before drawing a broader conclusion.'],
          ['08:20','Student asks, "Do I need another quote?" Teacher says, "Explain why this one supports your claim."','The prompt points toward reasoning; the student may need a model of the connection.'],
          ['13:10','Teacher reads three first attempts, then models the phrase "This matters because..." using one example.','The teacher changes instruction after inspecting work, relevant to CSTP 5B.'],
          ['21:30','Student A adds a second quotation; Student B explains a connection; Student C gives an oral explanation but has not written it.','Different responses require differentiated follow-up; a single completion count would conceal them.']
        ])+table(['Fictional work sample','First attempt','Revision / additional evidence'],[
          ['A','"The library should stay open. The survey says students need a quiet place."','"The library should stay open. The survey says students need a quiet place. The survey also says students study after school." The connection remains implicit.'],
          ['B','"The library should stay open because students study."','"The library should stay open because students need a quiet place. The survey matters because students without that space at home would have somewhere to complete their work."'],
          ['C','A claim and one survey detail, with no written explanation.','Oral response: "The number shows how many students could use the space." Written revision is incomplete when class ends.']
        ])),
        section('Post-observation Clip 1: interpret the evidence',transcript('Student learning, lesson video, and feedback',[
          ['00:10','Candidate','Looking at the work first, what did students learn and where is the evidence less clear?'],
          ['00:36','Teacher','B explains the connection. A still adds information without explaining why. C told me the reasoning but did not get it onto the page.'],
          ['01:15','Candidate','Let us replay lesson 13:10. What did you notice in the first attempts that led you to change the model?'],
          ['01:48','Teacher','They copied the quotation. I realized I had named the parts but had not thought aloud about the connection.'],
          ['02:20','Candidate','That is a specific use of assessment evidence to adjust instruction. When we compare A and B, what might we keep and what needs another model?'],
          ['03:05','Teacher','Keep reading the first attempts during the lesson. Next time I need to contrast a response that lists evidence with one that explains it.'],
          ['03:40','Candidate','What does C\'s oral explanation add, and what should we avoid concluding from the incomplete writing?'],
          ['04:05','Teacher','C may understand the connection. I need another way to check and time to help transfer that explanation into writing.']
        ],'At Post-observation Clip 1, 01:15-02:20, we replayed the lesson and linked the teacher\'s adjustment to CSTP 5B. I identified a concrete strength: she changed the model after inspecting first attempts. At 03:40-04:05, the oral evidence prevented us from treating incomplete writing as proof of absent understanding. The conversation produced a more specific next step than a general recommendation to differentiate.')),
        section('Post-observation Clip 2: co-determine next steps',transcript('A goal, support, and a follow-up',[
          ['00:10','Candidate','Of the options we discussed, which would be most useful and feasible in your next lesson?'],
          ['00:36','Teacher','A comparison of two explanations, then a chance to tell a partner why one is stronger before writing.'],
          ['01:02','Candidate','What evidence would tell us whether that supported the reasoning, rather than only producing longer responses?'],
          ['01:28','Teacher','The revised response needs to explain why the evidence supports the claim. I would keep the same descriptor and include incomplete work.'],
          ['02:00','Candidate','I can help choose contrasting examples from the work and rehearse the think-aloud with you. Shall we review six matched pairs next Thursday?'],
          ['02:32','Teacher','Yes. I also want to ask students what they changed and why, especially those who explain more orally than in writing.'],
          ['03:00','Candidate','Then our goal is clearer evidence of the reasoning connection, with oral and written evidence kept distinct. I will record the plan and the support I committed to.']
        ],'At Post-observation Clip 2, 00:10-01:28, the teacher selected the next action and the evidence criterion. At 02:00-03:00, we added a specific coaching resource and follow-up date. The agreement preserves teacher agency and makes my support accountable. It is a plan for another learning cycle, not evidence that the next lesson already improved.')),
        section('A workable recording arrangement',p('For the post-observation conversation, place the camera facing both participants, with the lesson video on a device they can view together. Keep the playback audio audible and refer clearly to lesson time versus meeting-clip time. Commentary uses the meeting-clip timestamp; it can then identify the lesson segment being discussed. Submit the required notes and work product as their own evidence, not a web link in place of an upload.'))
      ],
      evidence:evidence(['Full lesson observation recorded, at least twenty minutes.','CSTP-focused notes and at least one student work example used in the meeting.','Post-observation discussion includes lesson video, work, strengths, and growth.','One to three clips, within fifteen minutes total, with precise commentary.','Next steps, resources, and support are jointly determined.'],'Which observation and work sample support the next coaching step, and what evidence challenges your interpretation?')
    },
    {
      id:'c3-reflect',area:'c3',title:'Reflect: sustain teacher and leader growth',focus:'Evaluate the partnership and specify your next learning cycle.',rubrics:'3.6, 3.7',parts:'Part J',guide:[3,26],
      lecture:[
        section('Use the teacher\'s feedback as evidence',p('Compare your intentions as coach with what the teacher experienced. Identify a moment that supported inquiry and one that limited it. Explain the implications for your next coaching practice and for the role of coaching at the school. Claims about trust or agency should be grounded in the conversation and feedback.')+p('Keep observed outcomes separate from planned improvement. The current lesson can show a teaching adjustment and variation in work. The next lesson has not happened merely because it was planned. Reflection can be strong while acknowledging uncertainty.')),
        section('Finish with a coherent record',p('Review the links among the selected CSTP elements, lesson plan, observation notes, work, clips, commentary, and reflection. The lesson recording is used in the coaching process; the submitted meeting clips have their own requirements. Do not confuse a sample transcript with required video evidence.')+p('Part J allows up to four written pages or a video explanation up to six minutes. Keep official template text and formatting intact, redact identifying information as required, and check that every uploaded file opens and corresponds to the intended part.'))
      ],
      walkthrough:[
        section('Worked Part J response',fiction+model(p('This cycle strengthened my ability to make an instructional conversation specific. The teacher and I selected CSTP 5A and 5B around a question she identified in student work. At Post-observation Clip 1, 01:15-02:20, replaying the lesson helped us recognize that she had changed instruction after reading first attempts. That evidence made my affirmation concrete and gave us a starting point for examining the remaining difficulty.')+p('The teacher\'s fictional feedback was that comparing A, B, and C helped her think, but some of my questions came before she had finished examining the work. I recognized a tendency to accelerate the conversation toward a next step. In my next coaching cycle, I will leave an uninterrupted evidence-inspection interval, ask the teacher to offer the first interpretation, and invite an alternative explanation before suggesting a resource. I will review a short segment with my mentor and ask the teacher whether these changes increased her influence on the conversation.')+p('Our next instructional step is to compare contrasting explanations, include oral rehearsal, and review matched work with the same reasoning descriptor. I committed to helping choose examples and meeting the following Thursday. The current evidence does not establish durable teacher growth or improved graduation outcomes. It establishes a focused learning conversation and an agreed follow-up. At the school level, I would advocate protected follow-up time so observation becomes part of continuing inquiry rather than a single event.'))+why('The reflection connects a strength, a limitation, teacher feedback, a future coaching practice, and a school-level implication. It keeps completed evidence separate from future commitments.')),
        section('The complete Cycle 3 record',table(['Part','Evidence','Version 09 limit / condition'],[
          ['A','School coaching practices and volunteer teacher.','Up to 5 pages.'],
          ['B / C','Classroom and lesson narrative / teacher lesson plan.','B up to 4 pages; C includes work-product description.'],
          ['D / E','Pre-observation clips / commentary.','2 clips up to 6 minutes each; E up to 8 pages or 10 minutes.'],
          ['F / G','Observation notes / student work used in discussion.','One file each; at least one work-product example.'],
          ['H / I','Post-observation clips / commentary.','1-3 clips, at least 1 minute each, up to 15 minutes total; I up to 8 pages or 10 minutes.'],
          ['J','Reflection.','Up to 4 pages or 6 minutes.']
        ])),
        section('What the gap app contributes across the three cycles',p('The app makes the public outcome pattern visible and checkable. Cycle 1 adds local inquiry and a reasoned proposal. Cycle 2 adds actual collaborative implementation. Cycle 3 adds direct observation and coaching. The quality of the submission depends on those connections, not on the number of charts or the polish of the narrative.'))
      ],
      evidence:evidence(['Teacher feedback is analyzed, not merely quoted.','Reflection connects to specific coaching evidence.','Professional-growth and follow-up commitments are feasible.','Every required part is accounted for and identifying information handled.'],'What will you do differently in your next coaching conversation, and how will you know whether it helped?')
    }
  );
})();
