/* Prompt locations checked against the supplied Version 09 response templates. */
(() => {
  'use strict';
  const {p,table,model}=window.COURSE_HELPERS;
  const link=(url,text)=>`<a href="${url}" target="_blank" rel="noreferrer">${text}</a>`;
  const maps={
    'c1-investigate':{
      ask:'Why does this equity gap warrant attention, and how do the different sources support your analysis?',
      refs:'Part A, Sections I-III and Section IV, questions 1-5',
      rows:[['IV.1: Selection and quantitative rationale','Use the English Learners graduation history, counts, and denominators. Explain the recurring within-year disparity and the limits of comparing source years.'],['IV.2-3: Qualitative sources and patterns','Identify three different local sources. Compare what they reveal, including counterexamples, with the public pattern.'],['IV.4-5: Gap, research, and school purpose','Define the gap, explain relevant research, and connect the inquiry to verified school vision, mission, or goals.']],
      gap:'Full Report, Graduation in All Indicators, and the English Learners timeline support the quantitative portion. They cannot supply your local qualitative findings or the school\'s verified goals.',
      example:'Jordan High\'s reported 2025 graduation rates are 70.8% for English Learners and 85.9% schoolwide, a -15.1-point difference. In the fictional local inquiry, accounts, observations, and documents suggest uneven access to usable feedback, but also show successful in-class support. The combination justifies investigating access; it does not establish a cause of the graduation gap.',
      why:'The response connects the quantitative pattern to a qualified interpretation of local evidence. The complete walkthrough supplies the three-year table and explains the distinct sources.'
    },
    'c1-plan':{
      ask:'Which contributing conditions can the school address, and how do they lead to one defensible problem statement?',
      refs:'Part B, Section I, questions 1-4; Section II, problem statement',
      rows:[['I.1-2: Contributing conditions','Connect possible institutional or structural factors to Step 1 evidence and explain their implications for learning or well-being.'],['I.3-4: Research and educational need','Use relevant literature to examine the proposed explanation; identify a school-level need rather than blaming a reporting group.'],['II: Problem statement','Name the selected group, indicator, gap, and actionable area of need in one coherent statement.']],
      gap:'Indicator details help check the context. A second gap in attendance can prompt a question, but does not prove why the graduation difference exists.',
      example:'The fictional records point to inconsistent opportunities to act on feedback and incomplete support handoffs. The school-level need is a usable next step during the school day, with responsibility for checking follow-through. This is a plausible contributing condition to investigate, not a demonstrated explanation of every noncompletion.',
      why:'The problem follows from the earlier evidence, identifies something school leaders can influence, and keeps a possible mechanism separate from a proven cause.'
    },
    'c1-act':{
      ask:'Why do these proposed strategies fit the problem, and what changed after leadership feedback?',
      refs:'Part C, questions 1-5',
      rows:[['1-3: Strategies and alignment','Explain how the strategies would be applied, address the problem and contributing factors, and align with the school\'s purpose.'],['4: Feedback and revision','Report targeted feedback on each strategy and the resulting adjustment.'],['5: Buy-in and implications','Explain how you would involve school and community partners and anticipate implementation implications.']],
      gap:'The saved report gives the feedback conversation an evidence-based starting point. Your actual feedback record establishes what a leader said and what you changed.',
      example:'In the fictional feedback discussion, the leader questioned whether after-school-only support would reach learners with other obligations. I revised the proposal to include protected revision time during instruction and a named person to check support handoffs.',
      why:'The response shows the original proposal, the access concern raised through feedback, and a specific revision. It does not claim the proposal has already raised graduation.'
    },
    'c1-reflect':{
      ask:'What did evidence and feedback teach you about your own equity-focused leadership?',
      refs:'Part D, questions 1-3',
      rows:[['1: Feedback and partner buy-in','Explain why you sought particular feedback and how it influenced your approach to buy-in.'],['2: Strengths and growth','Use evidence from Steps 1-3 to evaluate how you addressed the selected group\'s equity needs.'],['3: Professional learning','Identify a specific learning goal and a feasible next step grounded in that analysis.']],
      gap:'Return to the public pattern to explain your starting assumption. The evidence of your growth is the change in your reasoning and actions, not a new chart.',
      example:'I initially equated more support hours with greater access. The local counterexamples and leader feedback changed that assumption. My next learning goal is to examine who can use a proposed support before recommending expansion.',
      why:'The reflection names an initial assumption, evidence that challenged it, and a concrete professional learning need.'
    },
    'c2-investigate':{
      ask:'What professional-learning context, educational focus, and group membership will support a meaningful community of practice?',
      refs:'Part A, Section I, questions 1a-d and 2; Section II, questions 1-5',
      rows:[['I.1-2: Professional-learning context','Analyze existing training, collaboration, communities of practice, and adult learning research; explain implications for facilitation.'],['II.1: Agreed educational focus','Explain the focus selected with leadership guidance, its supporting data, and its connection to school goals.'],['II.2-5: Membership and relationships','Explain roles, reasons for inclusion, demographics, positionality, and how the group can advance learning or well-being.']],
      gap:'The graduation pattern can help justify attention to equitable completion. Current work and the local professional-learning context establish the group\'s specific focus.',
      example:'The public pattern gives a reason to investigate access, but does not select the community for us. In the fictional case, teacher, language-development, and counseling perspectives help examine how feedback and support pathways operate across settings.',
      why:'The response explains the contribution of different roles without treating participation or agreement as something a public report can establish.'
    },
    'c2-plan':{
      ask:'How did colleagues help define the problem and choose a strategy they can implement and examine?',
      refs:'Parts B-C: planning agenda and minutes; Part D, Sections II and III, questions 1-4 in each',
      rows:[['D.II.1-4: Collaborative problem definition','Explain data analysis, differentiated student-group evidence, facilitation, and alignment with school goals and relevant standards.'],['D.III.1-3: Strategy and rationale','Show the collaborative choice, relevant evidence base, learning plan, anticipated challenges, and expected improvement.'],['D.III.4: Monitoring','Explain how the group will monitor and analyze initial implementation. Parts B-C document the planning meeting.']],
      gap:'Use a focused public-data packet to open discussion. The minutes, work samples, and group reasoning must show how the instructional problem and strategy were chosen.',
      example:'The fictional group examined contrasting explanations and agreed to test a feedback-and-revision routine. We would record whether the routine occurred and compare first attempts with revisions using a shared descriptor, rather than treating added word count as better reasoning.',
      why:'The strategy, learning need, and monitoring plan are connected. Evidence of implementation is distinguished from evidence about student learning.'
    },
    'c2-act':{
      ask:'What do the implementation meetings show about your facilitation and the group\'s learning?',
      refs:'Parts E-H: implementation records, products, and clips; Part I, questions 1-5',
      rows:[['I.1-2: Purpose and analysis','Use clip numbers and timestamps to explain how you established purpose and supported examination of implementation data.'],['I.3-4: Decisions and participation','Show how the group reached understanding, how viewpoints and feedback mattered, and how you maintained focus and monitored progress.'],['I.5: Next steps','Explain how the group determined next implementation steps; connect the commentary to what the submitted clips actually show.']],
      gap:'The original public report remains background. New implementation data, collaborative products, and authentic recordings now carry the evidentiary weight.',
      example:'In the fictional meeting, I asked colleagues to identify the sentence connecting evidence to a claim. The comparison exposed a weakness in our descriptor, and the group revised it. In a real response, I would anchor this account to the submitted clip and actual timestamp.',
      why:'The account links a facilitation move to the group\'s response and decision. It does not substitute a polished summary for an observable interaction.'
    },
    'c2-reflect':{
      ask:'What do implementation results and participant feedback reveal about your facilitation?',
      refs:'Part J, questions 1-4',
      rows:[['1: Leadership, results, and feedback','Analyze your influence on progress, strengths, growth needs, and equitable facilitation using specific records.'],['2-3: Professionalism and context','Examine integrity, equity, diverse viewpoints, and the school conditions that supported or challenged the work.'],['4: Next learning goals','Identify professional learning goals and next steps based on the experience.']],
      gap:'The public outcome explains why the concern mattered. It cannot establish that a short series of meetings improved graduation or that participants experienced equitable facilitation.',
      example:'The fictional group\'s disagreement improved the descriptor, but I would also examine whose interpretations changed the decision and whose voices were less visible. Selected work samples support a bounded account of learning, not a schoolwide treatment effect.',
      why:'The reflection evaluates the leadership process as well as the results and acknowledges limits that matter to the next decision.'
    },
    'c3-investigate':{
      ask:'How should the school\'s coaching practices and the volunteer teacher\'s experience shape this coaching cycle?',
      refs:'Part A, Section I, questions 1-5; Section II, questions 1-3',
      rows:[['I.1-3 and I.5: Existing practices','Analyze frequency, intended outcomes, processes, teacher input, and the role of CSTP.'],['II.1: Volunteer teacher','Describe experience, assignment, coaching history, and use of CSTP.'],['I.4 and II.2-3: Implications','Explain how context informs orientation, meetings, observation evidence, and strategies for anticipated challenges.']],
      gap:'Schoolwide outcomes and language context can inform background questions. They do not evaluate this teacher or describe the observed class.',
      example:'I would ask the volunteer teacher about prior coaching and what they want to understand in current work. In the fictional case, contrasting writing leads to a question about how learners use feedback, not a diagnosis derived from the school\'s graduation rate.',
      why:'The focus develops through the teacher\'s evidence and experience. School context is not substituted for a teacher-specific inquiry.'
    },
    'c3-plan':{
      ask:'How did you and the teacher agree on a focus and an evidence plan for the lesson?',
      refs:'Part B, question 1a-e; Part C: lesson plan; Part D: clips; Part E, questions 1-4',
      rows:[['B.1a-e and C: Lesson context','Explain learning goals, prior learning, setting, student assets and needs, resources, and other relevant context.'],['E.1-3: Shared focus','Show teacher self-assessment, review of the plan and work product, and joint selection of one or two CSTP elements.'],['E.4: Observation process','Explain the jointly reviewed coaching process and the CSTP-focused data to be collected; anchor commentary to the clips.']],
      gap:'The public report remains context. The teacher\'s question, lesson plan, and learners\' assets determine what will be observed.',
      example:'The fictional teacher and candidate agree to examine how feedback informs revisions and how the teacher responds to evidence of learning. They plan to retain contrasting work, including oral explanations, rather than judging understanding only by completed writing.',
      why:'The plan makes the shared instructional question observable and preserves teacher ownership of the focus.'
    },
    'c3-act':{
      ask:'How did lesson evidence help you and the teacher examine practice and determine next steps?',
      refs:'Parts F-H: observation notes, student work, and clips; Part I, questions 1-3',
      rows:[['I.1: Joint evidence analysis','Explain how you supported assessment of learning, shared CSTP-focused evidence, and co-analyzed lesson video and work.'],['I.2: Practice and growth','Show discussion of effective practice and missed opportunities, then jointly selected next steps and responsibilities.'],['I.3: Feedback on coaching','Explain teacher feedback about your coaching and what it reveals about your strengths and growth needs.']],
      gap:'No additional public chart replaces the lesson recording, observation notes, student work, or teacher interpretation required here.',
      example:'In the fictional post-observation discussion, an oral explanation complicates an incomplete written response. The teacher and candidate decide to include oral rehearsal and compare matched work in a follow-up. They have agreed on a next step, not yet demonstrated sustained improvement.',
      why:'The next step follows from contrasting evidence and joint interpretation. The response distinguishes an agreement from a completed outcome.'
    },
    'c3-reflect':{
      ask:'What did the teacher\'s feedback and the coaching evidence teach you about supporting professional growth?',
      refs:'Part J, questions 1-3',
      rows:[['1: Coaching strengths and growth','Evaluate your coaching using the teacher\'s feedback and the agreed CSTP focus; explain why particular growth needs matter.'],['2: Two-way conversation','Use Steps 1-3 evidence to examine teacher voice, ownership, and joint interpretation.'],['3: Equitable leadership','Reflect on continuous improvement and the potential contribution of coaching to equitable schooling.']],
      gap:'The public concern frames the wider purpose. Evidence of your coaching comes from the partnership, not from annual schoolwide outcomes.',
      example:'The fictional teacher\'s feedback suggests that examining contrasting work was helpful, but that I sometimes moved to another question too quickly. My next step is to leave time for inspection and invite the teacher\'s interpretation before offering a resource.',
      why:'The reflection uses specific feedback to identify a change in coaching practice rather than claiming general success.'
    }
  };
  const refs={
    equity:{title:'Look beyond a deficit description',cite:'Ladson-Billings, G. (2006). From the achievement gap to the education debt: Understanding achievement in U.S. schools. Educational Researcher, 35(7), 3-12.',url:'https://doi.org/10.3102/0013189X035007003',use:'This foundational conceptual article redirects attention from a snapshot of unequal outcomes toward accumulated historical, economic, sociopolitical, and moral obligations. It can help a leader ask about opportunities and institutional conditions rather than define learners by a deficit.',limit:'This is a conceptual argument, not an evaluation of the local feedback routine. It helps frame inquiry; it does not establish the cause of the English Learners graduation difference.'},
    leadership:{title:'Leadership, access, and school conditions',cite:'Grissom, J. A., Egalite, A. J., & Lindsay, C. A. (2021). How Principals Affect Students and Schools: A Systematic Synthesis of Two Decades of Research.',url:'https://wallacefoundation.org/report/how-principals-affect-students-and-schools-systematic-synthesis-two-decades-research',use:'Use this synthesis to examine leaders\' influence on instruction, climate, collaboration, and resources. For the English learner case, it helps frame questions about access and school processes rather than treating language status as an explanation.',limit:'It does not identify the cause of this school\'s gap. The publisher notes subsequent challenges to the magnitude of its achievement-effect estimates; do not use those estimates as a promised local result.'},
    dropout:{title:'Graduation pathways and responsive support',cite:'Rumberger, R., et al. (2017). Preventing Dropout in Secondary Schools. What Works Clearinghouse.',url:'https://ies.ed.gov/ncee/wwc/PracticeGuide/24/Published',use:'Recommendations 1 and 2 help examine monitoring and individualized support. In this case, ask whether a referral becomes usable assistance and who checks follow-through.',limit:'Recommendation 1 has minimal evidence and Recommendation 2 moderate evidence in this guide. The guide does not establish that the fictional referral routine will improve graduation.'},
    learning:{title:'Professional learning that changes practice',cite:'Darling-Hammond, L., Hyler, M. E., & Gardner, M. (2017). Effective Teacher Professional Development. Learning Policy Institute.',url:'https://learningpolicyinstitute.org/product/effective-teacher-professional-development-report',use:'The review identifies features such as active learning, collaboration, models, feedback, reflection, and sustained engagement. Use these to explain how colleagues will learn through examining and trying a practice, rather than only hearing a presentation.',limit:'The review describes features across effective programs. It does not establish that every feature independently causes improvement or that three meetings reproduce a sustained program.'},
    writing:{title:'A research-informed writing strategy',cite:'Graham, S., et al. (2016). Teaching Secondary Students to Write Effectively. What Works Clearinghouse.',url:'https://ies.ed.gov/ncee/wwc/PracticeGuide/22/Published',use:'Recommendation 1 supports explicit strategy instruction through a Model-Practice-Reflect cycle. Recommendation 3 addresses using writing assessment to inform instruction and feedback. These connect directly to the fictional feedback-and-revision inquiry.',limit:'The guide rates Recommendation 1 strong and Recommendation 3 minimal evidence. Our shared descriptor and cross-subject adaptation are teaching examples, not an independently evaluated intervention.'},
    coaching:{title:'Coaching as professional learning',cite:'Kraft, M. A., Blazar, D., & Hogan, D. (2018). The effect of teacher coaching on instruction and achievement: A meta-analysis of the causal evidence. Review of Educational Research, 88(4), 547-588.',url:'https://doi.org/10.3102/0034654318759268',use:'This synthesis of 60 causal studies supports examining coaching as a way to develop instruction. It offers a rationale for sustained, evidence-focused professional learning, not for rating a teacher from a school dashboard.',limit:'Much of the evidence concerns literacy coaching in prekindergarten and elementary settings. Applicability to this high-school partnership needs justification, and program-level findings do not demonstrate an effect of a single conversation.'}
  };
  const literature={
    c1:{ids:['equity','leadership','dropout'],where:'Part A, Section IV.4; Part B, Section I.3; strategy rationale in Part C',example:'Rumberger et al. (2017) inform our attention to monitoring and responsive support. In the fictional local records, a referral does not consistently lead to a confirmed appointment. Together, the literature and these records justify examining follow-through; neither establishes that this process caused the graduation disparity.',why:'The citation supports the rationale. The local record supports the observation. The conclusion remains conditional.'},
    c2:{ids:['learning','writing'],where:'Part A, Section I.1d; Part D, Section III.1-4',example:'Drawing on Darling-Hammond, Hyler, and Gardner (2017), the fictional community builds learning around examining work, trying the routine, and discussing feedback. The writing guide informs the selected strategy. We will document implementation and compare work rather than assume that participation itself improved learning.',why:'Research informs both how adults learn and what strategy they test. The response still needs evidence of the group\'s actual decisions and work.'},
    c3:{ids:['coaching','writing'],where:'Coaching rationale and reflection in Parts A, E, I, and J; consider the research-related distinctions in Rubrics 3.6-3.7',example:'Kraft, Blazar, and Hogan (2018) provide a broader rationale for instructional coaching, while their study contexts limit direct transfer to this high-school lesson. In the fictional partnership, we co-analyze contrasting work and agree on a follow-up; we cannot claim that one conversation produced the program-level effects reported in the literature.',why:'The example makes the relevance and transfer limit explicit. Actual teacher feedback and lesson evidence must establish what happened here.'}
  };
  const pages=[
    ['school','Select School','school.png','Confirm the school and district before opening Full Report. A matching name is not enough.','The same identity anchors all your public-data records. This is preparation, not a substitute for local context.'],
    ['report','Full Report','report.png','Begin with the broad pattern, then locate the English Learners graduation result and its reporting year.','Cycle 1 Part A: identify a concern. Cycle 2 Part A: explain the broader educational focus. Cycle 3 Part A: provide background, not a teacher rating.'],
    ['indicators','All Indicators','indicators-graduation.png','Inspect the graduation subgroup table: 46 graduates / 65 in the accountability denominator, 70.8%; schoolwide 85.9%.','Cycle 1: support an accurately bounded quantitative claim. Cycles 2-3: distinguish schoolwide indicators from current group or classroom evidence.'],
    ['timeline','Equity Timeline Explorer','timeline-english-learners.png','Select Graduation and English Learners. Inspect the available years, comparison groups, and source definitions before describing change.','Cycle 1: build the required historical analysis after refreshing and verifying the applicable years. Cycles 2-3: keep annual outcomes separate from short-cycle learning evidence.'],
    ['support','CalAPA Cycle 1 Support','support.png','Compare the public-data packet with the local evidence still needed. Treat suggested questions as a starting point for inquiry.','Cycle 1 Parts A-C: connect investigation to a proposal. For later cycles, carry forward the concern without predetermining colleagues\' or the teacher\'s conclusions.'],
    ['about','About This Project','about.png','Review the app\'s purpose and source boundaries before relying on an exported result.','All cycles: preserve attribution, verify source values, and distinguish public records from your own leadership evidence.']
  ];
  function cycleId(id){return ['c1','c2','c3'].includes(id)?id:'c1';}
  function researchBlock(id){
    const c=literature[cycleId(id)];
    return `<section class="literature-example"><h2>Use literature to justify a decision</h2><p class="question-ref">${c.where}</p>${model(p(c.example))}<p><strong>Why this addresses the task:</strong> ${c.why}</p><p><a href="#literature/${cycleId(id)}">Read the sources, their uses, and their limits</a></p></section>`;
  }
  window.MENTOR={
    maps,
    promptGuide(unit,mode){
      const m=maps[unit.id];if(!m)return '';
      return `<section class="prompt-guide" aria-labelledby="prompt-heading"><p class="kicker">Connect to the assessment</p><h2 id="prompt-heading">${m.ask}</h2><p class="question-ref">${m.refs} &middot; <a href="sources/CalAPA_C${unit.guide[0]}_AssessmentGuide.pdf#page=${unit.guide[1]}" target="_blank" rel="noreferrer">Official guide</a></p><p class="source-note">Plain-English prompt summaries, not replacement template wording. Address every applicable subprompt in the original template.</p>${table(['Prompt location','What your response needs to explain'],m.rows)}<dl><dt>What the Equity Gap app contributes</dt><dd>${m.gap}</dd></dl>${mode==='walkthrough'?`<h3>A focused teaching example</h3><p class="fiction">Fictional local reasoning paired with the saved public evidence; not a submission to copy.</p>${model(p(m.example))}<p><strong>Why it addresses the question:</strong> ${m.why}</p>`:''}</section>`;
    },
    literature(id){
      id=cycleId(id);const c=literature[id];
      return `<p class="kicker">Cycle ${id.slice(1)} &middot; Research in practice</p><h1>Using literature in this cycle</h1><p class="deck">Use a source to explain a decision, test an interpretation, or justify a strategy. A citation is useful when its contribution is clear.</p><article class="reading"><p>The sources below are a focused starting set, not a required reading list or a separate literature-review assignment. Select literature that fits your actual question, learners, and setting. Read the source before citing it, and keep its limitations with your claim.</p><p><strong>Assessment connection:</strong> ${c.where}. ${id==='c1'?'For Cycle 1, the official Version 09 guide directs candidates to embed citations in the response rather than provide a separate citation list.':`Follow the Cycle ${id.slice(1)} guide and template directions for citing sources.`}</p>${id==='c1'?window.LEARNING_SUPPORT.cedarResearch():''}${id==='c1'?'<h2>Additional Harbor High example: secondary-school research</h2><p>The following retained sources concern the fictional graduation, feedback, and referral inquiry in Harbor High, with separately labeled Jordan public context. They do not explain Cedar Grove attendance.</p>':'<p>Primary example: Canyon View Grade 9 writing. Cycle 2 uses 24 sampled learners; Cycle 3 uses Chen\'s separate class of 28. These source discussions inform decisions, not claims of a measured research effect here.</p>'}${researchBlock(id)}${c.ids.map(key=>{const r=refs[key];return `<section class="literature-entry"><h2>${r.title}</h2><p class="citation">${link(r.url,r.cite)}</p><p>${r.use}</p><p class="note"><strong>Boundary:</strong> ${r.limit}</p></section>`;}).join('')}<section><h2>From reading to response</h2><p>First name what the local evidence shows. Then explain the specific idea from the source that informs your interpretation or choice. Finally, state what you will do and what remains uncertain. Do not let a general research finding stand in for evidence from your setting.</p><p><a href="#unit/${id}-plan/lecture">Return to planning</a> &middot; <a href="#connections/${id}">Cycle overview</a></p></section><p class="source-note">Source links and publication details checked October 6, 2026. These examples support learning; they do not certify an assessment score.</p></article>`;
    },
    gap(id){
      id=cycleId(id);const uses={c1:'The reports help you identify and describe an equity concern. Your local qualitative inquiry, literature, leadership feedback, and reasoning turn that concern into a justified proposal.',c2:'The reports help explain why the educational focus matters. Your colleagues must help define the problem, choose and implement the strategy, and examine new evidence together.',c3:'The reports provide school context. The volunteer teacher\'s experience, goals, lesson, and student work determine the coaching inquiry.'};
      return `<p class="kicker">Cycle ${id.slice(1)} &middot; Public evidence to local inquiry</p><h1>Working with the Equity Gap app</h1><p class="deck">${uses[id]}</p><article class="reading"><p>The app brings school identification, outcome reports, subgroup comparisons, historical records, and source notes together. That saves time assembling the public-data starting point and helps make an equity question inspectable.</p><p>${link('https://explorer.chrisboosalis.com','Open the Equity Gap app')} &middot; <a href="#source/report">Read the saved Full Report</a></p><p class="source-note">Screenshots captured October 6, 2026. These are saved public-school examples, not a live data connection. The fictional local story is Harbor High; its meetings and classroom evidence are not findings about the public school.</p><nav class="page-toc" aria-label="Gap app pages">${pages.map(([key,name])=>`<a href="#gap-${key}" data-jump="gap-${key}">${name}</a>`).join('')}</nav>${pages.map(([key,name,img,read,use])=>`<section class="gap-page" id="gap-${key}"><p class="kicker">${name}</p><h2>${read}</h2><figure><a class="image-link" href="assets/gap-app-pages/${img}" target="_blank" rel="noreferrer" aria-label="Open full-size ${name} screenshot"><img src="assets/gap-app-pages/${img}" alt="Saved Equity Gap app ${name} page for the public-school example" width="1440" height="1080" loading="lazy"></a><figcaption>${use}</figcaption></figure><p><a href="#source/${key}">Read the saved ${name} page</a></p></section>`).join('')}<section><h2>Turn the report into a supported claim</h2><div data-chart="graduation-gaps"></div>${model(p('The 2025 English Learners graduation rate is 70.8%, compared with 85.9% schoolwide. The -15.1-percentage-point difference warrants investigation of access to graduation pathways. It does not identify the reason for the difference.'))}<p>Use official California data and graphics where appropriate. Verify Analyzer values against the official source, retaining counts, denominators, reporting periods, and source qualifications beside the figure. Complete the required CalAPA tables and explain what local evidence is needed to answer the next question.</p><p>${link('https://explorer.chrisboosalis.com','Explore the Equity Gap app')} &middot; <a href="#unit/${id}-investigate/walkthrough">Follow the Cycle ${id.slice(1)} worked example</a> &middot; <a href="#app-reference/${id}">All report and indicator connections</a></p></section></article>`;
    },
    cycleMap(id){
      id=cycleId(id);return `<section class="cycle-prompt-map"><h2>Follow the questions through the cycle</h2>${table(['Step and prompt locations','Teaching sequence'],Object.entries(maps).filter(([key])=>key.startsWith(id)).map(([key,m])=>[`<a href="#unit/${key}/lecture">${key.split('-')[1].replace(/^./,x=>x.toUpperCase())}</a><br><small>${m.refs}</small>`,`${m.ask}<br><a href="#unit/${key}/walkthrough">Worked response and explanation</a>`]))}<p><a href="#gap/${id}">See how the Gap app supports this cycle</a> &middot; <a href="#literature/${id}">Using literature in this cycle</a></p></section>`;
    },
    researchBlock
  };
})();
