/* Plain-language orientation and prompt crosswalks for the supplied Version 09 guides.
   Prompt locations identify the closest instructional alignment, not exclusive scoring rules. */
(() => {
  'use strict';
  const D = window.GUIDE_CONTENT;
  const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pdf = (cycle, page, label) => `<a href="sources/CalAPA_C${cycle}_AssessmentGuide.pdf#page=${page}" target="_blank" rel="noreferrer">${esc(label)}</a>`;
  const maps = {
    c1: [
      ['Investigate','A','1.1','Section I; Section IV, question 1',11,'Analyze the numbers and select a student group.','Three years of chronic absenteeism data show a persistent difference for students with disabilities. Explain the pattern and why it warrants investigation.'],
      ['Investigate','A','1.2','Section II; Section IV, questions 2-3',11,'Investigate experiences and conditions behind the numbers.','Compare student interviews, a family listening session, and attendance procedures. Explain where the sources agree or differ.'],
      ['Investigate','A','1.3','Section III; Section IV, questions 4-5',12,'Explain the equity concern and its connection to school priorities.','Bring the numerical and qualitative findings together. Explain how access to attendance support relates to the school\'s commitment to equitable participation.'],
      ['Plan','B','1.4','Section I, questions 1-4',17,'Investigate potential contributing factors.','Families describe difficulty obtaining help, and a document review finds inconsistent referrals. Examine this possible institutional factor using local evidence and research.'],
      ['Plan','B','1.5','Section II, problem statement',17,'Define a focused problem the school can address.','Frame the problem around access to timely attendance support, not an assumption that families do not value attendance.'],
      ['Act','C','1.6','Questions 1-3',21,'Propose strategies that address the established problem.','Propose a coordinated attendance-support process with accessible family communication and clear referral responsibilities. Explain why it fits the evidence.'],
      ['Act','C','1.7','Questions 4-5',21,'Use leadership feedback to refine the proposal.','A leader identifies staffing limits. Revise referral responsibilities and explain feasibility, needed support, and implementation implications.'],
      ['Reflect','D','1.8','Questions 1-3',24,'Examine your leadership learning and growth needs.','Explain how feedback revealed that you underestimated staff workload and why you would involve implementation staff earlier next time.']
    ],
    c2: [
      ['Investigate','A','2.1','Section I, questions 1a-d and 2',11,'Understand how educators currently learn together.','Examine whether teacher meetings allow colleagues to analyze student writing together or mainly exchange announcements. Connect your analysis to student learning.'],
      ['Investigate','A','2.2','Section II, questions 1-5',13,'Choose a data-based focus and appropriate partners.','Writing samples raise questions about multilingual learners\' opportunities to explain reasoning. Explain why four teachers and their perspectives belong in the inquiry.'],
      ['Plan','B-D','2.3','Part D, Word Section II (guide Section I), questions 1-4; Parts B-C planning records',17,'Define the problem with the group.','Teachers jointly examine work and identify inconsistent opportunities for oral rehearsal before writing. Show how colleagues helped define the problem.'],
      ['Plan','B-D','2.4','Part D, Word Section III (guide Section II), questions 1-4; Parts B-C planning records',18,'Select one evidence-based strategy together.','After reviewing relevant research, the group chooses a structured partner-discussion routine and agrees how to learn it, use it, and monitor initial results.'],
      ['Act','E-I','2.5','Part I prompts about purpose, viewpoints, feedback, focus, and progress; Parts E-H evidence',25,'Facilitate participation and learning during implementation.','When members disagree about student work, invite each interpretation and ask what evidence supports it. Document how the group reaches decisions.'],
      ['Act','E-I','2.6','Part I prompts about data, shared interpretation of results, and next steps; Parts E-H evidence',25,'Help the group interpret results and decide what comes next.','Compare work collected during implementation. Identify promising patterns and exceptions, then jointly decide what to adjust or continue investigating.'],
      ['Reflect','J','2.7','Questions 1-4',29,'Evaluate your facilitation using results and member feedback.','Members report that a few voices dominated early meetings. Explain what you changed, what the evidence shows, and what you still need to improve.']
    ],
    c3: [
      ['Investigate','A','3.1','Section I, questions 1-5: school practices and CSTP use',11,'Understand the school\'s coaching and feedback context.','Investigate whether observations usually emphasize evaluation, professional learning, or both. Explain implications for your coaching approach.'],
      ['Investigate','A','3.1','Section II, questions 1-3: volunteer teacher and implications',12,'Understand the teacher\'s experience and plan the partnership.','The teacher describes past observations as largely evaluative. Explain how this informs your approach to a collaborative learning partnership. Both Part A sections support Rubric 3.1.'],
      ['Plan','B-E','3.2','Part E, questions 1-4; Parts B-C context and lesson plan; Part D clips',18,'Plan the observation with the teacher.','The teacher wants to examine questioning. Jointly choose one or two CSTP elements within the same domain and agree to collect questions, student responses, and participation evidence.'],
      ['Act','F-I','3.3','Part F observation evidence; related lesson analysis',20,'Document and analyze focused observation evidence.','Record specific questions and student responses tied to the agreed focus. Distinguish what you observed from your interpretation.'],
      ['Act','F-I','3.4','Part I: student-learning assessment and joint discussion of teaching; Parts F-H supporting evidence',22,'Conduct a two-way learning conversation.','Review a lesson-video segment and student work together. Ask what the teacher notices about which questions elicited explanations.'],
      ['Act','F-I','3.5','Part I: jointly determined growth steps; Part H meeting evidence',23,'Agree on professional-growth steps together.','Choose a questioning adjustment with the teacher. Agree on resources, the teacher\'s next action, and the coaching support you will provide.'],
      ['Reflect','J','3.6','Questions 1-2; teacher feedback also discussed in Part I',27,'Evaluate this coaching process and partnership.','The teacher says your questions helped but you offered solutions too quickly. Analyze that feedback alongside evidence from the conversations.'],
      ['Reflect','J','3.7','Question 3',27,'Consider your broader role as an equitable instructional leader.','Explain how evidence-based coaching can support teacher growth and more equitable learning opportunities without claiming that one lesson proves lasting improvement.']
    ]
  };
  const lessons = {
    c1: {
      title: 'Cycle 1: Investigate an equity concern',
      intro: 'You investigate an equity gap by examining school commitments, allocated resources, students\' access to support, and actual outcomes together. CalAPA connects the resources and intended outcomes in improvement plans with actual performance for underserved students. An attendance or graduation disparity may prompt the inquiry, but the difference alone does not establish its cause. A funded service is not proof that the intended students can use it.',
      steps: [
        ['Investigate','A','Analyze the three most recent years of quantitative data for one state indicator and select a student group for closer investigation. Quantitative data are numerical results, such as attendance rates. Examine at least three different qualitative sources to understand experiences, practices, and conditions behind those results.','Attendance data show higher chronic absenteeism among students with disabilities than among students overall. Interview students, hold a family listening session, and examine attendance procedures. Compare the sources rather than assuming why students are absent.'],
        ['Plan','B','Investigate potential contributing factors and develop a focused problem statement. Institutional or structural factors are school practices, policies, arrangements, or conditions that may contribute to the concern.','Families report difficulty obtaining assistance, and your document review reveals no consistent referral process. Investigate that potential factor using research and local evidence. Frame the problem around access to timely support.'],
        ['Act','C','Propose strategies that address the identified problem. Obtain feedback from administrators or educational leaders familiar with the setting and use it to strengthen the proposal.','A leader identifies staffing limitations in your proposed attendance-support process. Revise responsibilities and explain how the feedback makes the proposal more workable. Cycle 1 does not require implementation results.'],
        ['Reflect','D','Use evidence from the earlier steps to examine what the process revealed about your leadership, how feedback shaped the strategy and support for it, and where you need to grow.','Explain how feedback revealed that you underestimated workload and why you would involve implementation staff earlier in future planning. Reflect on your leadership, not only the school\'s shortcomings.']
      ]
    },
    c2: {
      title: 'Cycle 2: Lead collaborative improvement',
      intro: 'You lead a community of practice: a group of educators or educational partners learning together to improve practice. Work with three to five partners, in addition to yourself. Together, identify a problem of practice, select one evidence-based strategy, implement it, and examine initial results. Your role is to facilitate participation and learning, not simply distribute tasks.',
      steps: [
        ['Investigate','A','Examine how educators currently learn together, identify a focus supported by student data and leadership guidance, and select appropriate partners.','Student writing raises questions about opportunities for multilingual learners to explain their reasoning. Examine existing teacher collaboration and bring together four teachers whose responsibilities connect directly to the concern.'],
        ['Plan','B-D','Facilitate a planning meeting in which the group examines evidence, identifies a problem of practice, and chooses a strategy. Parts B and C contain the planning agenda and minutes; Part D explains the problem and strategy.','Teachers identify inconsistent opportunities for oral rehearsal before writing. After examining relevant research, they choose a structured partner-discussion routine and agree on evidence to collect. The decision must be genuinely collaborative.'],
        ['Act','E-I','Support implementation through at least three implementation meetings, separate from the planning meeting. Submit agendas (E), minutes (F), collaborative products (G), three video clips (H), and commentary (I).','Teachers try the routine and bring writing samples and implementation notes. Ask which responses show more developed reasoning and where that pattern is absent. Help the group examine variation and agree on next steps. Discussing a strategy without trying it is not implementation.'],
        ['Reflect','J','Use initial implementation results, member feedback, and specific evidence to analyze your equitable facilitation, strengths, growth needs, and next steps.','Members report that some voices dominated early meetings. Explain what you changed to broaden participation, what evidence shows about the change, and what you still need to improve.']
      ]
    },
    c3: {
      title: 'Cycle 3: Coach a teacher',
      intro: 'Partner with a volunteer teacher through a pre-observation meeting, a lesson observation, and a post-observation meeting. Together, select one or two elements within the same domain of the California Standards for the Teaching Profession (CSTP) to focus the coaching. The teacher helps interpret the evidence and determine next steps.',
      steps: [
        ['Investigate','A','Learn about the school\'s coaching practices and the volunteer teacher\'s experience. Explain how this context shapes your approach. Part A has separate school-context and teacher-context sections; both contribute to Rubric 3.1.','The teacher describes previous observations as largely evaluative. Explain how that experience informs your efforts to establish a collaborative learning partnership.'],
        ['Plan','B-E','Conduct the pre-observation meeting. Understand the lesson, student assets and needs, and teacher goals. Agree on the focus and evidence to collect. Submit classroom information (B), the lesson plan (C), two meeting clips (D), and commentary (E).','The teacher wants to understand how questioning supports explanations. Jointly select relevant CSTP elements and agree to document questions, student responses, and participation.'],
        ['Act','F-I','Observe the lesson live for at least 20 minutes and record the full observation, analyze evidence and student work, and conduct the post-observation conversation. Submit observation notes (F), student work (G), meeting clips (H), and commentary (I).','Review a lesson segment and student work together. Ask what the teacher notices, then jointly choose a change to try next. The lesson recording supports the conversation; submitted meeting clips demonstrate your coaching interactions.'],
        ['Reflect','J','Use the teacher\'s feedback and cycle evidence to examine your coaching and instructional leadership.','The teacher says your questions supported reflection but you sometimes offered solutions too quickly. Examine the partnership under 3.6; consider the broader implications for equitable instructional leadership under 3.7.']
      ]
    }
  };
  function glance(id) {
    const n=D.cycles[id].number;
    return `<section class="cycle-glance" id="glance-${id}"><h3>Cycle ${n} at a glance</h3><p>Each rubric has its own row. Read its complete descriptors with the related evidence in the cycle page; no one response determines a score alone.</p><table class="rubric-map"><caption class="sr-only">Cycle ${n}: steps, parts, purposes, and rubric focus</caption><colgroup><col style="width:15%"><col style="width:7%"><col style="width:23%"><col style="width:55%"></colgroup><thead><tr><th scope="col">Step</th><th scope="col">Part</th><th scope="col">Purpose</th><th scope="col">Rubric focus</th></tr></thead><tbody>${maps[id].map(([step,part,rubric,prompt,page,purpose])=>{
      const [,title,target]=D.rubrics[rubric];
      return `<tr data-rubric="${rubric}"><th scope="row" data-label="Step">${esc(step)}</th><td data-label="Part">${part}</td><td data-label="Purpose">${esc(purpose)}</td><td data-label="Rubric focus"><p><a href="#cycle/${id}/rubric-${rubric.replace('.','-')}"><strong>${rubric}: ${esc(title)}</strong></a></p><p>${esc(target)}</p><p class="prompt-location source-note">${esc(prompt)}</p></td></tr>`;
    }).join('')}</tbody></table></section>`;
  }
  function cycleBody(id) {
    const lesson=lessons[id], c=D.cycles[id];
    return `<h2>${lesson.title}</h2><p class="kicker">${esc(c.title)}</p><h3>What you will do</h3><p>${esc(lesson.intro)}</p>${lesson.steps.map(([step,part,work,example],i)=>{
      const s=Object.values(D.steps).filter(x=>x.rubrics[0].startsWith(`${c.number}.`))[i];
      return `<section class="overview-step"><h3>${step}: Part${part.includes('-')?'s':''} ${part}</h3><p><strong>Rubric${s.rubrics.length>1?'s':''} ${s.rubrics.join(', ')}.</strong> ${esc(work)}</p><p class="scenario"><strong>Example:</strong> ${esc(example)}</p></section>`;
    }).join('')}${glance(id)}<p><a href="#cycle/${id}">Continue to the Cycle ${c.number} manual, evidence requirements, and rubric discussions</a></p>`;
  }
  function home() {
    return `<header class="guide-heading"><p class="kicker">Overview</p><h1>Understanding CalAPA</h1><p class="deck">The California Administrator Performance Assessment (CalAPA) evaluates your ability to carry out educational leadership work. It is not a single sit-down examination.</p><p>You complete three cycles of work in a school or educational setting, collect evidence, and explain your decisions, actions, and learning. Your submissions include written responses and supporting materials. Cycles 2 and 3 also include video clips showing specified leadership interactions. <strong>The responses explain your work; the evidence helps demonstrate what you actually did.</strong></p></header>
    <figure class="assessment-map"><button type="button" class="map-expand" data-map-expand aria-label="Expand the CalAPA assessment map" aria-haspopup="dialog"><picture><source media="(max-width:600px)" srcset="assets/calapa-assessment-map-mobile.png"><img src="assets/calapa-assessment-map.png" width="1800" height="1100" alt="Three leadership cycles: investigate an equity concern and develop a proposal; facilitate colleagues implementing a strategy; coach a volunteer teacher. Each follows Investigate, Plan, Act, Reflect."></picture><span class="map-expand-icon"><i data-lucide="expand" aria-hidden="true"></i></span></button><figcaption>Instructional map based on the Version 09 guides. <a href="assets/calapa-assessment-map.png" target="_blank" rel="noreferrer">Open full-size map</a> &middot; <a href="#map-text" data-jump="map-text">Read the map as text</a>.</figcaption></figure>
    <section class="passing-standards" id="passing-standards" aria-labelledby="passing-heading">
    <h2 id="passing-heading">Scoring and passing CalAPA: 2026-2027</h2>
    <p>CalAPA uses <strong>analytic rubrics</strong>: each rubric evaluates a particular aspect of your leadership using the evidence you submit. Trained, calibrated assessors apply the scoring criteria. Calibration means demonstrating that they can apply those criteria consistently. <a href="https://www.ctc.ca.gov/performance-assessment/resources/admin-design-standards/" target="_blank" rel="noreferrer">CTC assessor standards</a>.</p>
    <h3>Rubric points and cycle totals</h3>
    <p>Each scorable rubric receives <strong>1-5 points</strong>. The rubric scores within one cycle are added to produce your <strong>total cycle score</strong>. That total is compared with the <strong>cut score</strong>, the minimum total required to pass that cycle. The cut score is the threshold, not the name for the score you earn. <a href="https://www.ctcexams.nesinc.com/content/docs/CalAPA_ScoreReportExp.pdf" target="_blank" rel="noreferrer">Official score-report explanation</a>.</p>
    <table class="passing-score-table"><caption class="sr-only">CalAPA passing standards for the 2026-2027 operational administration</caption><thead><tr><th scope="col">Cycle</th><th scope="col">Rubrics</th><th scope="col">Maximum points</th><th scope="col">Passing score</th></tr></thead><tbody><tr><th scope="row">Cycle 1</th><td>8</td><td>40</td><td><strong>15 points</strong></td></tr><tr><th scope="row">Cycle 2</th><td>7</td><td>35</td><td><strong>14 points</strong></td></tr><tr><th scope="row">Cycle 3</th><td>7</td><td>35</td><td><strong>14 points</strong></td></tr></tbody></table>
    <p class="source-note">Maximum points = number of rubrics multiplied by 5. Passing scores verified October 7, 2026 against the <a href="https://www.ctcexams.nesinc.com/Content/HTML_FRAG/GENRB_Passing_CalAPA.html" target="_blank" rel="noreferrer">official 2026-2027 passing standards</a>.</p>
    <p><strong>You do not need a 3 on every rubric to meet the cycle's passing score.</strong> Because scores are added within a cycle, a higher numeric score can balance a lower one. Each cycle must pass separately; points from Cycle 1 cannot make up a shortfall in Cycle 2 or 3.</p>
    <p class="scenario" id="scoring-example"><strong>Arithmetic example:</strong> Seven numeric scores of <strong>3 + 2 + 2 + 2 + 2 + 2 + 1 = 14</strong> meet Cycle 2's point threshold, provided the cycle is scorable. This illustrates the calculation, not a recommended performance target. A condition code cannot be balanced by points elsewhere.</p>
    <h3>What the five levels mean</h3>
    <ul id="rubric-levels"><li><strong>Levels 1 and 2:</strong> The evidence matches lower-level descriptions, such as limited analysis, unclear justification, or unsupported practice. Read the specific descriptors; a low numeric score is different from an unscorable submission.</li><li><strong>Level 3:</strong> Demonstrate the performance described in that rubric's Level 3 criteria. The essential question identifies the focus, but merely answering it or including a named document does not automatically earn a 3.</li><li><strong>Levels 4 and 5:</strong> Demonstrate all the preceding required criteria plus the additional qualities specified at the higher level. More pages, extra quotations, or additional qualitative sources do not automatically earn more points.</li></ul>
    <p><strong>Example from Rubric 1.1:</strong> Level 3 calls for analysis of three years of quantitative data and a justified student-group choice. Level 4 adds relevant additional data that clarify group differences. Level 5 also requires relevant research that informs your understanding of the equity issue. <a href="sources/CalAPA_C1_AssessmentGuide.pdf#page=14" target="_blank" rel="noreferrer">Read the complete Version 09 rubric</a>.</p>
    <h3>Condition codes and retakes</h3>
    <p id="condition-code-explanation">A <strong>condition code</strong> identifies a submission problem that prevents scoring, such as an unreadable file, an incorrect template, or insufficient required evidence. If any rubric receives a condition code, the cycle is reported as <strong>Not Scorable</strong>; remaining rubrics receive <strong>X</strong> rather than numeric scores. This is not a zero or an ordinary low score. Review the code with your program advisor, correct the identified problem, and follow the re-registration and resubmission requirements. <a href="https://www.ctcexams.nesinc.com/TestView.aspx?f=CACBT_SubmissionRequirementsConditionCodes_CalAPA.html" target="_blank" rel="noreferrer">Official submission requirements and condition codes</a>.</p>
    <p>If you do not meet a cycle's passing standard, seek support from your preparation program. A retake requires re-registration, applicable fees, and a complete submission for that cycle. It is scored in full, not merely as a replacement score for selected rubrics. You must receive your scores before re-registering, and the policy explains when previously submitted materials may be reused or revised. Follow the <a href="https://www.ctcexams.nesinc.com/Content/HTML_FRAG/GENRB_Passing_CalAPA.html#RetakePolicy" target="_blank" rel="noreferrer">CalAPA Retake Policy</a>.</p>
    </section>
    <article class="reading guide-reading novice-overview"><section id="map-text"><h2>The three cycles</h2><ul><li><strong>Cycle 1:</strong> Investigate an equity concern and develop a justified improvement proposal.</li><li><strong>Cycle 2:</strong> Lead colleagues as they implement a strategy and examine initial results.</li><li><strong>Cycle 3:</strong> Coach a teacher using evidence from a lesson and student work.</li></ul><p>Each cycle follows <strong>Investigate, Plan, Act, and Reflect</strong>, but the activities differ. Developing a proposal in Cycle 1 is different from implementing a strategy in Cycle 2 or conducting a coaching conversation in Cycle 3.</p></section>
    <section><h2>How the manuals, parts, and rubrics fit together</h2><p>The <strong>assessment guide</strong>, or manual, explains the activities, required evidence, scoring rubrics, and submission specifications. Associated <strong>templates</strong> contain the prompts you answer about your work.</p><p>A <strong>step</strong> is a stage of the work. A <strong>part</strong> is a labeled component you submit. A <strong>rubric</strong> describes how an aspect of your performance is evaluated. For example, Cycle 1's Investigate step leads to Part A. Within Part A, quantitative analysis, qualitative analysis, and the combined equity-gap explanation align with Rubrics 1.1, 1.2, and 1.3.</p><p>There are <strong>22 rubrics: eight in Cycle 1, seven in Cycle 2, and seven in Cycle 3</strong>. Each describes performance across five levels. Read the relevant rubric before undertaking the work, while selecting evidence, and when preparing your response. Completing an activity does not automatically establish its quality.</p><p>For example, saying that you obtained feedback documents an event. Explaining what changed because of that feedback shows how it informed your leadership decision. The summaries below explain rubric targets; they do not replace the full scoring descriptors.</p><p class="fiction">All short scenarios below are hypothetical illustrations, not findings or responses to copy into a submission. Existing extended teaching examples remain available in each cycle.</p></section>
    <section id="overview-limits"><h2>Plan the evidence before beginning</h2><p><strong>Cycle 1:</strong> A permits 5 response pages excluding quantitative and qualitative tables; B and C permit 5 pages each; D permits 5 written pages OR 5 minutes. <a href="#cycle/c1/limits">Cycle 1 submission map</a>.</p><p><strong>Cycle 2:</strong> A permits 5 pages, D 4, and G 10. H requires exactly three clips, up to 5 minutes each. I permits 8 pages OR 10 minutes; J permits 4 pages OR 5 minutes. B, C, E, and F have no page maximum specified, but the meeting records are required. <a href="#cycle/c2/limits">Cycle 2 submission map</a>.</p><p><strong>Cycle 3:</strong> A permits 5 pages and B 4. D requires two clips, up to 6 minutes each. E and I each permit 8 pages OR 10 minutes. H permits one to three clips, each at least 1 minute, totaling no more than 15 minutes. J permits 4 pages OR 6 minutes. C, F, and G have no page maximum specified. <a href="#cycle/c3/limits">Cycle 3 submission map</a>.</p><p>Limits apply to each complete part, not each question. Original template text counts toward the limit. A video commentary or reflection is your explanation; it is different from a meeting clip documenting the interaction. Plan permissions, dates, sound, framing, and participants before recording. Cycle 2 requires actual implementation over several weeks. Cycle 3 requires an actual teacher partnership and a recorded lesson, although the lesson recording itself is not submitted.</p><p><a href="#equity-gap-help">Explore the Equity Gap app with Jordan High data and Cycle 1 question links</a>. Public reports cannot supply local interviews, collaborative decisions, lesson evidence, or your leadership reflection.</p><p class="source-note">Version 09 specifications: Cycle 1 printed pp. 24-25; Cycle 2 pp. 30-32; Cycle 3 pp. 28-31. Complete directions and file requirements appear in each cycle.</p></section>
    ${Object.keys(lessons).map(id=>`<section id="overview-cycle-${D.cycles[id].number}">${cycleBody(id)}</section>`).join('')}
    <section id="overview-data"><h2>Data and preparation</h2><p>The <a href="https://explorer.chrisboosalis.com" target="_blank" rel="noreferrer">Equity Gap app</a> can help you explore potential Cycle 1 concerns. <strong>Verify its numbers against official sources before using them</strong>, including the school, year, indicator, student group, measure, and denominator. Relevant sources include the <a href="https://www.caschooldashboard.org/" target="_blank" rel="noreferrer">California School Dashboard</a> and <a href="https://www.cde.ca.gov/ds/" target="_blank" rel="noreferrer">CDE data resources</a>. Use state graphics where appropriate while completing the required CalAPA tables and analysis. No specific state graphic is required.</p><p>Plan access to data and participants, meeting and observation schedules, permissions, confidentiality protections, and evidence collection. Follow your program's procedures and the applicable manual. Video, meeting records, and observation evidence must come from the actual work; a polished narrative cannot replace missing activities.</p></section>
    <section id="official-materials"><h2>Official manuals and current materials</h2><ul class="source-list"><li><a href="https://www.ctc.ca.gov/performance-assessment/resources/" target="_blank" rel="noreferrer">CTC manuals and templates</a><small>Locate the CalAPA assessment guides and templates for all three cycles.</small></li><li><a href="https://www.ctcexams.nesinc.com/TestView.aspx?f=HTML_FRAG/CalAPA_AssessmentMaterials.html" target="_blank" rel="noreferrer">Assessment materials and updates</a><small>Check guides, templates, corrections, and supplementary guidance.</small></li><li><a href="https://www.ctcexams.nesinc.com/TestView.aspx?f=HTML_FRAG/CalAPA_TestPage.html" target="_blank" rel="noreferrer">Official CalAPA information</a><small>Review submission information, policies, preparation resources, and passing standards.</small></li></ul><p class="source-note">This overview explains the supplied Version 09 materials. Confirm the version applicable to your submission. The official prompts, full rubric descriptors, and submission specifications govern your work. <a href="#sources">Saved guides and templates</a> are reference copies and do not update automatically.</p></section></article>`;
  }
  window.NOVICE_OVERVIEW={home,glance,maps};
})();
