/* Narrative teaching layer. Saved public observations and fictional local work stay distinct. */
(() => {
  'use strict';
  const {p, table, chart, model}=window.COURSE_HELPERS;
  const unitLink=(id,text,mode='walkthrough')=>`<a href="#unit/${id}/${mode}">${text}</a>`;
  const sourceLink=(id,text)=>`<a href="#source/${id}">${text}</a>`;
  const section=(id,title,html)=>({id,title,html});
  const fiction=p('<strong>Fictional local example.</strong> From this point, Harbor High accounts, decisions, meetings, and classroom evidence are invented for teaching. They are not findings about the school in the public report.');
  const research=(unit,explanation)=>{
    const row=window.RESEARCH_CONTENT.lectures.find(r=>r.unit===unit);
    const reference=row.source.replace(/\n[^:]+:\s*/,': ');
    return `<aside class="tutorial-research"><h3>Connect to Intro to Research</h3>${p(explanation)}<p class="source-note research-reference"><a href="https://research.chrisboosalis.com" target="_blank" rel="noreferrer">${reference}</a></p></aside>`;
  };
  const tabs=()=>'';
  const readings=sections=>`<details class="contents-index"><summary>On this page</summary><nav class="page-toc" aria-label="On this page">${sections.map(s=>`<a href="#${s.id}" data-jump="${s.id}">${s.title}</a>`).join('')}</nav></details><article class="reading tutorial-reading">${sections.map(s=>`<section id="${s.id}"><h2>${s.title}</h2>${s.html}</section>`).join('')}</article>`;
  const partMap=(cycle,rows)=>table(['Step and submission parts','What the pieces establish together'],rows)+`<p class="source-note">Instructional summary of the supplied 2026-27 Version 09 guide. <a href="sources/CalAPA_C${cycle}_AssessmentGuide.pdf#page=8" target="_blank" rel="noreferrer">Read the original Cycle ${cycle} evidence table</a>. <a href="#sources">All prompts, templates, and submission specifications</a>.</p>`;
  const handoff=(title,text)=>`<aside class="tutorial-handoff"><h3>${title}</h3>${p(text)}</aside>`;
  const introduction=[
    section('intro-purpose','Start with the leadership, not the paperwork',
      p('Imagine that a school is improving overall, yet one group of students is still graduating at a lower rate. You can see the difference. You cannot yet explain it. What should a leader do next? Choosing a program immediately would skip the investigation. Writing a careful description without involving anyone would leave the concern untouched. Leadership requires moving from noticing a pattern to understanding conditions, making decisions with people, and examining what follows.')+
      p('That is the work at the center of CalAPA, the California Administrator Performance Assessment. It is a performance assessment: you make your leadership visible through evidence from work you actually undertake. The written responses explain your judgment; the records, work products, and required video show the basis for that explanation. The point is not to sound like an administrator. It is to show how you reason and act as one.')+
      p('A cycle is a complete round of inquiry and learning. Each cycle asks you to investigate, plan, act, and reflect. The familiar words do different jobs: investigate before deciding what the problem is; plan a response that fits the evidence; carry out the leadership work required in that cycle; then examine what the experience taught you. Reflection should be something you could not have written honestly before doing the work.')),
    section('intro-cycles','Three cycles, three different leadership responsibilities',
      p('Cycle 1 takes the school-improvement view. You identify an equity concern, examine possible contributing conditions, and develop strategies that you revise through feedback. Cycle 2 takes the collaborative-learning view. You facilitate a community of practice that identifies a problem, implements a strategy, and learns from implementation evidence. Cycle 3 takes the coaching view. You work with a volunteer teacher to agree on an instructional focus, observe a lesson, examine evidence together, and determine next steps.')+
      table(['Cycle','The central question','What completes the account'],[
        ['1: Investigate an equity concern','What deserves attention, what conditions may contribute, and what response is justified?','A supported analysis, a feasible proposal revised through feedback, and reflection on your leadership.'],
        ['2: Lead learning with colleagues','How can we learn together while implementing a response to an agreed problem?','Actual collaborative decisions, implementation evidence, recorded facilitation, and reflection.'],
        ['3: Coach a teacher','How can a teacher and coach use lesson evidence to support instructional growth?','A jointly chosen focus, observation and student work, recorded coaching conversations, and reflection.']
      ])+
      p('Notice the change in the word <em>act</em>. In Cycle 1, seeking feedback and revising the proposed strategies is substantive action; it is not evidence that the proposal has already improved graduation. Cycle 2 requires implementation with a group. Cycle 3 requires observation and coaching with a teacher. A well-written proposal cannot substitute for those later performances.')+
      p('Our teaching case connects the cycles so you can follow the reasoning. That connection is an instructional choice, not an additional requirement to carry one intervention, group, or teacher through all three assessments. Each cycle must satisfy its own requirements in your setting.')),
    section('intro-components','How the steps, parts, and evidence fit together',
      p('The four steps organize the work. The lettered parts organize what you submit. A rubric describes the quality of performance being evaluated. These are three views of the same cycle, not three separate assignments. One step may produce several parts because a plan, a record of a conversation, and your explanation establish different things.')+
      p('For example, an agenda shows what you intended to discuss. Minutes preserve selected discussion and decisions. A work product shows something the group examined or produced. A video lets the assessor observe an interaction. Commentary explains a particular choice you made, why you made it, and what followed. Reflection considers what this experience reveals about your leadership and your next learning need. None becomes stronger merely by repeating the others.')+
      table(['Component','Its job in the account','A useful question'],[
        ['Context and investigation','Explain whose situation matters and what is known.','What supports this focus, and what remains uncertain?'],
        ['Plan and rationale','Connect the evidence to an intended response.','Why this choice, with these people, in these conditions?'],
        ['Records, work, and required video','Make actual activity available for inspection.','Where can another reader see what happened?'],
        ['Narrative and commentary','Explain the reasoning and significance of the evidence.','What does this example establish about my decision or leadership move?'],
        ['Reflection','Examine learning, limitations, and next steps.','What changed in my thinking, and what will I do differently?']
      ])+
      research('orientation','A claim is what we ask the reader to accept. Evidence is the record we use to support it. A warrant is the reason that record supports the claim. An attendance list can support who attended a meeting; it cannot, on its own, support a claim that participants shaped the decision. That second claim needs evidence of their influence.')),
    section('intro-case','One English Learners example to make the process concrete',
      p('The saved Equity Gap report gives us a starting point. In reporting year 2025, Jordan High has a schoolwide graduation rate of 85.9% and an English Learners rate of 70.8%. The difference is -15.1 percentage points. The English Learners row reports 46 graduates and an accountability denominator of 65; schoolwide reports 170 and 198. Those source-year denominators are not all currently enrolled students.')+
      chart('graduation-gaps')+
      p('The chart helps us ask about access to graduation pathways. It does not say that English learner status caused the outcome, identify a particular teacher, or tell us which response will help. Schoolwide includes English Learners, and the other displayed groups can overlap. We must investigate the opportunities and school processes students actually encounter.')+
      p('The chart and saved report contain real public aggregate observations, not toy results. To teach the next moves without inventing claims about that school, the local story shifts to fictional Harbor High. Its student accounts, assignment packets, meetings, work samples, and coaching conversations are teaching examples. They illustrate how evidence can inform a decision; they are not evidence of events at Jordan High.')+
      p('In that fictional story, some learners receive a score or referral without a usable next step, while others describe effective feedback during class. Cycle 1 examines that uneven access. Cycle 2 follows colleagues as they study a feedback-and-revision routine. Cycle 3 follows one teacher as she investigates how students use feedback to explain their reasoning. The shared concern becomes more specific because new evidence is introduced, not because the graduation chart proves a classroom diagnosis.')),
    section('intro-gap','Where the Equity Gap app does valuable work',
      `<div class="gap-app-intro">${p('The Equity Gap app brings the public-data starting point into one place: school identification, outcome reports, group comparisons, historical records, and source qualifications. Its value is that you can move from a schoolwide headline to a specific, inspectable question without treating an average as everyone\'s experience.')}<p><a class="button-link" href="https://explorer.chrisboosalis.com" target="_blank" rel="noreferrer">Open the Equity Gap app <i data-lucide="external-link" aria-hidden="true"></i></a></p></div>`+
      p('For Cycle 1, those reports can supply part of the public quantitative evidence and help focus the local inquiry. For Cycle 2, they can establish why a concern deserves collaborative attention, while current work and group decisions establish the instructional problem. For Cycle 3, they provide school context, while the teacher and lesson evidence determine the coaching focus. The app remains useful as the scale changes, but it does not supply every kind of evidence.')+
      p('Reports, tables, and charts belong beside the claims they support. Our cycle tutorials therefore introduce a report when a decision needs it, explain what to notice, and then show the next source or action required. Inspect the saved chart, download its table or image from the evidence library, or open the separate Equity Gap App to explore a school. Viewing a stored figure does not create a new analysis or local evidence.')),
    section('intro-start','Begin with a question you can investigate',
      p('Before opening a response template, be able to explain the cycle in ordinary language: the concern, the people involved, the decision you must make, and the evidence that will help. Then use the official prompts and rubrics to check whether your account answers what is actually asked. Clear reasoning and compliance belong together; neither replaces the other.')+
      p('Start with the English Learners report in Cycle 1. We will follow it from a descriptive difference to a question, from that question to local evidence, and from the evidence to a proposal. The later tutorials show why collaboration and coaching require different performances rather than another copy of the same report.')+
      `<div class="tools"><a class="primary-action" href="#connections/c1">Begin Cycle 1 <i data-lucide="arrow-right" aria-hidden="true"></i></a>${unitLink('orientation','Orientation overview','lecture')}<a href="#sources">Official guides and submission parts</a></div>`+
      p('<span class="source-note">This is an instructional interpretation of the supplied 2026-27 Version 09 guides, not an assessor-scored exemplar or a replacement for the applicable official requirements.</span>'))
  ];

  const cycles={
    c1:{title:'Cycle 1: From an equity concern to a justified proposal',deck:'Learn why the outcome pattern, local investigation, proposed strategies, feedback, and reflection belong in one connected account.',next:'c2',sections:[
      section('c1-purpose','Understand the whole cycle first',
        p('At the start, we know that an English Learners graduation disparity deserves attention. At the end, we want a defensible proposal and an explanation of what we learned while developing it. The work between those points matters: the public pattern identifies a concern, local inquiry examines possible conditions, research informs the response, and feedback tests the proposal against the setting.')+
        p('The components fit together as a chain of reasoning. Part A establishes the concern and evidence. Part B explains the contributing conditions and focused problem. Part C shows the strategies and how feedback shaped them. Part D looks back at the decisions and your leadership learning. If the proposal could have been written before the inquiry, the investigation has probably not done enough work.')+
        partMap(1,[['Investigate / Part A','Quantitative and qualitative evidence support the selected group, equity concern, and connection to school goals.'],['Plan / Part B','Contributing conditions, relevant research, and a focused problem connect the concern to an actionable scope.'],['Act / Part C','Strategies, leader feedback, revisions, and implications show how the proposal becomes more defensible.'],['Reflect / Part D','Evidence from the earlier steps supports an account of leadership learning and growth.']])),
      section('c1-report','Get the report for a reason',
        p('Open Select School in the Equity Gap app. For the saved example, confirm Jordan High, Los Angeles Unified, CDS 19647331934454. This is not a clerical detail: a similar school name would give the whole inquiry the wrong foundation. Then open Full Report to see the broad pattern before settling on a focus.')+
        p('Now inspect Graduation in All Indicators. Compare the schoolwide result with the English Learners row, including the counts and denominator. We retain Graduation Rate as the selected indicator. Attendance, language progress, or assessment results may add context, but they answer different questions and should not silently replace it.')+
        chart('graduation-gaps')+
        model(p('In the saved 2025 report, English Learners have a graduation rate of 70.8%, compared with 85.9% schoolwide. The difference is -15.1 percentage points. This supports a preliminary inquiry into equitable access to graduation pathways. It does not identify why the difference occurred.'))+
        handoff('Contribution to Part A','The report supplies a descriptive public-data claim with a named group, measure, period, and comparison. It helps justify investigating the concern. It does not yet supply the required local qualitative analysis or a supported explanation.')+
        p(`${sourceLink('school','Selected school context')} &middot; ${sourceLink('report','Full saved report')} &middot; ${sourceLink('indicators','Detailed indicator reading')}`)),
      section('c1-history','Check whether the concern recurs, then preserve the evidence',
        p('In Equity Timeline Explorer, choose Graduation and English Learners explicitly. Do not assume that a saved timeline has the group you need: the original default graduation export in this packet selected a different group. The course separately preserves the English Learners records shown here.')+
        '<div data-history-table></div>'+
        p('English Learners are below schoolwide in each saved year. That recurring within-year disparity is useful evidence even while comparability across years needs qualification. The annual denominators change, these are not repeated observations of the same students, and historical graduation definitions and DASS variants need checking before a like-for-like change claim.')+
        p('Retain the report, the selected-group table, the source files, reporting years, and measure notes together. The supplied guide calls for the three most recent years of the selected indicator; a 2023-2025 teaching snapshot is not automatic proof that you have the current required years for your own submission. Verify the records and resolve discrepancies before relying on them.')+
        handoff('Why the app is useful here','It makes the move from a headline rate to a selected-group history practical. The leadership decision remains yours: explain why this concern warrants inquiry, rather than choosing whichever bar is largest.')+
        research('gap-app','One record here represents an aggregate group in a reporting year. Keeping that unit of analysis visible prevents us from writing as though the chart followed the same individual learners over time.')),
      section('c1-local','Move from an outcome to a condition you can investigate',
        fiction+
        p('We now leave the public report and enter the Harbor High teaching example. Ask how learners experience course-completion support. Student accounts can show how feedback is understood; observations can show whether time to use it actually occurs; assignment packets and referral procedures can show what the process asks students and adults to do. These sources have different jobs, so their agreement or disagreement can change the explanation.')+
        p('In the fictional Q1-Q3 record, several accounts and packets point to unclear next steps. But two learners describe useful in-class conferences, and one observed class provides a model and revision time. The counterexample matters: the finding is uneven access to usable feedback and follow-through, not that all support is ineffective or that English learners lack motivation.')+
        model(p('The public data establish a recurring graduation disparity. The fictional local evidence suggests that access to actionable feedback and an opportunity to use it varies across the reviewed courses. I would focus the proposal on those adult-controlled practices while investigating other plausible conditions. This limited inquiry does not explain the entire graduation gap.'))+
        handoff('How Parts A and B connect','Part A presents and analyzes the sources. Part B uses that analysis, together with relevant research, to justify a bounded problem. Repeating the graduation percentage in Part B does not explain a contributing condition.')+
        research('c1-plan','Problem, purpose, and question must point in the same direction. Once local evidence suggests a feedback-access problem, the next evidence must examine that process, rather than merely add more unrelated public indicators.')+
        p(unitLink('c1-investigate','Examine the complete Q1-Q3 example')+' &middot; '+unitLink('c1-plan','Follow the problem statement and research rationale'))),
      section('c1-response','Test the proposal through feedback, then reflect',
        p('In the fictional proposal, feedback and revision become part of class time, and a named adult checks whether a support referral becomes a usable next step. The proposal follows from the investigated condition. It is not a program selected because its name appeared in the report.')+
        p('The initial after-school-only idea changes when the leader asks about transportation and care responsibilities. That exchange belongs in Part C because it shows what feedback did to the strategy. The future pilot and its monitoring plan remain proposed work, not current implementation results. In Part D, the candidate explains the initial assumption, the challenge, the revision, and a concrete growth need.')+
        model(p('I first treated the gap as a reason to add more help. The local counterexamples and the leader\'s access question changed the proposal: the core revision opportunity would occur during instruction. I learned to examine who can use a support before increasing its availability. I cannot yet claim that this proposed change improves graduation.'))+
        p('The finished cycle is coherent when the same group and concern remain visible from analysis through reflection, and every change in direction is explained. The report opened the inquiry; your use of local evidence and feedback makes the leadership visible.')+
        p(unitLink('c1-act','Read the strategy and feedback example')+' &middot; '+unitLink('c1-reflect','Read the complete reflection')))
    ]},
    c2:{title:'Cycle 2: From a shared concern to collaborative learning',deck:'Understand how the group, planning records, implementation meetings, work products, video commentary, and reflection tell one story of facilitated learning.',next:'c3',sections:[
      section('c2-purpose','The work changes when colleagues become co-investigators',
        p('Cycle 2 is not Cycle 1 performed in a meeting. The central work is facilitating a community of practice that identifies a problem, chooses a strategy, implements it, and examines what happens. A community of practice is a group learning through shared work on a problem, not simply people who receive the same information.')+
        p('In the Harbor High teaching story, the concern remains English learners\' access to useful feedback and revision. The group must still examine the evidence and shape the focus. Presenting a finished plan for colleagues to approve would hide the very collaborative reasoning this cycle asks you to demonstrate.')+
        partMap(2,[['Investigate / Part A','Explain the professional-learning context, educational focus, and community membership.'],['Plan / Parts B-D','The planning agenda and minutes support the narrative explaining the jointly selected problem and strategy.'],['Act / Parts E-I','Implementation agendas, minutes, collaborative work products, three meeting clips, and commentary show the work and your facilitation.'],['Reflect / Part J','Implementation results and member feedback inform reflection on your leadership and the group\'s learning.']])),
      section('c2-report','Bring a focused evidence packet, not a predetermined answer',
        p('Return to the Gap app\'s Full Report for the selected school, then retrieve the English Learners graduation table and timeline. Keep the measure, years, counts, and qualifications attached. This compact packet explains why equitable completion warrants attention. It cannot describe the current professional-learning culture or select the group\'s instructional problem.')+
        '<div data-history-table></div>'+
        model(p('The saved English Learners graduation pattern gives our inquiry a school-level reason for attention. To identify a feasible instructional focus, the community needs current tasks, feedback, and work samples, alongside the local accounts and records. The annual public pattern cannot tell us whether a proposed writing routine fits those learners and tasks.'))+
        p('If the group also opens ELA in All Indicators, first check which population that result describes. The saved schoolwide ELA series is not an English-Learners-only finding. More charts do not necessarily mean a better rationale; keep a figure only when it answers a relevant question.')+
        handoff('Contribution to Part A','The Gap evidence can support the rationale for an educational focus. Your investigation of existing collaboration, selection of appropriate participants, and analysis of the local setting supply the rest. Do not present the report as evidence that colleagues agreed.')+
        p(`${sourceLink('report','Revisit the saved Full Report')} &middot; ${unitLink('c2-investigate','Read the group-selection example')}`)),
      section('c2-plan','Let local work shape the shared problem and strategy',
        fiction+
        p('The fictional community includes an English teacher, a mathematics teacher, an English language development specialist, a counselor, and the candidate as facilitator. Different expertise helps the group question an initial interpretation. The planning meeting begins with local work: can learners make a claim, select evidence, and explain the connection between them?')+
        p('The group narrows the concern to explanatory reasoning and adapts a model-practice-reflect routine with actionable feedback and protected revision time. The agenda organizes that inquiry. The minutes preserve the discussion and decisions. Part D explains why the selected problem and strategy follow from the evidence, including the relevant research, rather than merely reporting that a meeting occurred.')+
        p('Before implementation, agree what counts as evidence. A revised answer that adds words is not necessarily a better explanation. Use a shared descriptor, retain first attempts and revisions, and record whether students actually received the planned opportunity. That distinguishes implementation from the quality of student response.')+
        research('c2-plan','An operational definition turns a broad phrase such as "better reasoning" into something the group can examine consistently. Agreeing on the evidence before comparing results makes the later interpretation more defensible.')+
        p(unitLink('c2-plan','Study the planning decisions, descriptor, and strategy rationale'))),
      section('c2-act','Make implementation and group learning visible',
        p('Now the evidence must come from new work. Over the implementation meetings, participants bring work products, examine use of the routine, compare interpretations, and determine adjustments. In the supplied guide, the planning meeting is separate from the minimum three implementation meetings. The public report cannot stand in for those events.')+
        p('The fictional examples show why facilitation matters. When colleagues disagree about whether a longer revision is stronger, the candidate asks them to point to the sentence that connects evidence to the claim. The disagreement becomes an opportunity to clarify the descriptor rather than a vote about whose judgment wins.')+
        model(p('At the cited implementation-meeting moment, I asked members to identify the reasoning in the revised work before judging improvement. Their comparison revealed that our descriptor could reward added detail without an explanation. We revised the descriptor and agreed to re-examine contrasting examples. The record supports a change in the group\'s interpretation, not proof that the strategy closed a graduation gap.'))+
        p('The work product gives the discussion an object. The video shows the exchange. Commentary explains your move, the response, and its significance at a specific moment. Agendas and minutes add the planned purpose and recorded decisions. Together these parts show more than any one item can establish alone.')+
        handoff('Where the Gap report stops doing the evidentiary work','It remains background. Implementation logs, work products, actual meeting records, and video now support the account of what happened. An annual change in the public report is not a short-cycle measure of these meetings.')+
        p(unitLink('c2-act','Follow the three fictional meetings and annotated clips')+' &middot; <a href="#recording">Recording setup and commentary</a>')),
      section('c2-reflect','Reflect on what the group learned and how you led',
        p('Part J draws on implementation results and feedback from community members. Ask what the evidence supports, which findings are mixed, and how your facilitation influenced participation and decisions. A smooth meeting is not automatically a productive inquiry; disagreement can be valuable when it changes the work.')+
        p('In our case, the candidate can examine how the descriptor and routine changed, whether the records show implementation, and what selected work reveals. Differences in tasks and selected samples limit stronger claims. The account becomes credible by explaining those limits and the next decision, not by promising that a few meetings transformed schoolwide outcomes.')+
        p('Cycle 2 closes with an evidence-based account of collaborative learning. The next tutorial changes the scale again: a volunteer teacher and coach examine one lesson, using evidence specific to that teacher\'s question.')+
        p(unitLink('c2-reflect','Read the reflection and its evidence limits')))
    ]},
    c3:{title:'Cycle 3: From school context to a teacher-led coaching inquiry',deck:'Connect the teacher context, pre-observation conversation, lesson, student work, post-observation conversation, commentary, and reflection.',next:null,sections:[
      section('c3-purpose','Understand coaching as a shared investigation',
        p('Cycle 3 asks you to support the professional learning of a volunteer teacher. You investigate the coaching context, listen to the teacher\'s experience and question, agree on an observation focus, collect lesson evidence, and examine it together. The next step should emerge from that partnership rather than arrive as your diagnosis before the conversation begins.')+
        p('The California Standards for the Teaching Profession, or CSTP, give the observation a professional focus. They do not turn the school\'s public outcome rate into a rating of the teacher. In our fictional case, the teacher wants to understand whether learners can use feedback to explain their reasoning, rather than simply add more words.')+
        partMap(3,[['Investigate / Part A','Analyze existing coaching practices and the volunteer teacher\'s context and experience.'],['Plan / Parts B-E','Classroom and lesson narrative, teacher lesson plan, two pre-observation clips, and commentary establish the jointly selected focus and evidence plan.'],['Act / Parts F-I','Observation notes, student work, post-observation clips, and commentary support the analysis and next steps.'],['Reflect / Part J','The experience and teacher feedback support reflection on your coaching and further growth.']])),
      section('c3-report','Use the public report to ask, not to diagnose',
        p('Open the same school\'s Full Report and locate the English Learners graduation pattern. Retain it as background to the broader access concern. If you inspect English learner progress or language context in All Indicators, preserve the population and measure definitions: ELPI is not graduation, and neither identifies what happened in this teacher\'s classroom.')+
        table(['What we carry forward','What we must learn anew'],[['Saved public context: 2025 English Learners graduation 70.8%; schoolwide 85.9%.','The volunteer teacher\'s professional experience, coaching history, goals, and current classroom context.'],['A question about learners\' access to usable feedback and support.','Whether that question fits this teacher\'s evidence and priorities, and what focus the teacher helps choose.']])+
        model(p('The public report helps explain the broader school concern. It does not establish a weakness in this teacher\'s practice or describe the students in the observed class. I would begin with the teacher\'s account and examples of current work before agreeing on an observation focus.'))+
        handoff('Contribution to Part A','The report can inform school context. It cannot supply an analysis of the site\'s coaching practices, the volunteer teacher\'s experience, or the implications for your partnership. Those require direct, permitted local inquiry.')+
        p(`${sourceLink('report','Revisit the saved report')} &middot; ${unitLink('c3-investigate','Read the teacher-context example')}`)),
      section('c3-plan','Agree on what the lesson can help you understand',
        fiction+
        p('The Harbor High teacher teaches a Grade 10 English class with 28 learners, including nine currently identified as English learners. These are fictional classroom details, not the public graduation accountability group. The teacher brings contrasting writing and asks why some revisions add information without explaining the claim.')+
        p('In the pre-observation conversation, teacher and candidate examine that question, the lesson goals, student assets, and the planned work product. They co-select CSTP elements and agree what to collect. The existing model uses 2024 CSTP 5A and 5B within Standard 5; the detailed lesson reading links the official wording. The observation is designed around evidence of how the teacher gathers information about learning and uses it for a next teaching move.')+
        p('Now the parts have a clear relationship. The lesson plan records the intended learning. The classroom/lesson narrative explains the context and observation arrangement. The pre-observation clips show the shared decisions, and commentary explains how your coaching supported them. Agreement about evidence before the lesson makes the later conversation more focused and less like a surprise evaluation.')+
        p(unitLink('c3-plan','Follow the lesson plan and pre-observation examples'))),
      section('c3-act','Move from observation to a learning conversation',
        p('During the lesson, record what the teacher and learners say and do, and collect the agreed work products. An observation is a record of an event; an interpretation explains its possible meaning. Keeping them distinct gives the teacher something concrete to confirm, question, or explain.')+
        p('In the fictional lesson, the teacher examines first attempts and changes the model. One written revision still lists evidence without explaining it. Another makes the connection explicit. A third learner offers an explanation orally but has incomplete writing when time ends. These contrasting examples prevent the conversation from equating every unfinished written response with absent understanding.')+
        model(p('Comparing the lesson video with the work helped us distinguish a useful teaching adjustment from an unresolved learning need. The teacher had responded to first attempts, but some learners still needed support moving from an oral explanation to a written one. We agreed to compare contrasting explanations, include oral rehearsal, and examine matched work in the follow-up.'))+
        p('The post-observation conversation brings the video, CSTP-focused notes, and student work together. Invite the teacher\'s interpretation, examine both strengths and unresolved questions, and jointly determine the next step and support. The lesson recording serves the coaching process; the submitted pre- and post-observation meeting clips have their own requirements. Commentary should point to the actual interaction, not describe an ideal conversation that is absent from the clip.')+
        handoff('The evidence now belongs to the lesson and partnership','The Gap report is no longer the basis for judging this instructional move. The lesson, work, teacher interpretation, and coaching record support the account. No result from one lesson establishes an effect on schoolwide graduation.')+
        p(unitLink('c3-act','Inspect the observation notes, work A-C, and coaching excerpts')+' &middot; <a href="#recording">Recording and commentary guide</a>')),
      section('c3-reflect','Close the cycle without claiming the future has happened',
        p('Reflection asks what your coaching made possible, where it was limited, and how teacher feedback changes your next approach. In the fictional account, contrasting work helped the teacher think, but the candidate sometimes asked the next question before the teacher finished examining the evidence. That becomes a concrete professional-learning target: leave time for inspection and invite the teacher\'s interpretation before proposing a resource.')+
        p('An agreed follow-up is a commitment, not completed evidence of sustained growth. Your reflection can explain the commitment while being precise about what the current cycle demonstrates: a focused observation, an evidence-rich learning conversation, and a jointly selected next step.')+
        p('Look back across the three cycles. We began with a public outcome, investigated a local condition, followed a group learning through implementation, and examined a teacher\'s lesson with the teacher. The concern stayed recognizable while the evidence changed to match the decision. That is the organizing logic of this tutorial: each claim needs evidence suited to the work it describes.')+
        p(unitLink('c3-reflect','Read the coaching reflection')+' &middot; <a href="#home">Return to the complete overview</a>'))
    ]}
  };
  window.TUTORIAL={
    introduction(){return `<p class="kicker">California Administrator Performance Assessment</p><h1>CalAPA Mentor</h1><p class="deck">Understand the questions. Examine the evidence. Explain your leadership decisions.</p><nav class="cycle-path" aria-label="Choose your cycle">${[['1','Investigate an equity concern','From a public-data pattern to a justified proposal.'],['2','Lead learning with colleagues','From a shared problem to implementation and reflection.'],['3','Coach a teacher','From an agreed focus to evidence-informed professional growth.']].map(([n,title,detail])=>`<a href="#connections/c${n}"><span class="cycle-index">Cycle ${n}</span><span><strong>${title}</strong><small>${detail}</small></span><i data-lucide="arrow-right" aria-hidden="true"></i></a>`).join('')}</nav>${readings(introduction)}`;},
    render(cycle='c1'){
      if(!cycles[cycle])cycle='c1';
      const c=cycles[cycle];
      return `<p class="kicker">CalAPA tutorial</p><h1>${c.title}</h1><p class="deck">${c.deck}</p>${tabs(cycle)}${readings(c.sections)}<nav class="endnav" aria-label="Continue the tutorial"><a href="${cycle==='c1'?'#home':`#connections/c${Number(cycle.slice(1))-1}`}"><i data-lucide="arrow-left" aria-hidden="true"></i><span>${cycle==='c1'?'Introduction and overview':'Previous cycle'}</span></a><a href="${c.next?'#connections/'+c.next:'#sources'}"><span>${c.next?'Continue to Cycle '+c.next.slice(1):'Check the submission requirements'}</span><i data-lucide="arrow-right" aria-hidden="true"></i></a></nav><p class="source-note"><a href="#app-reference/${cycle}">Gap app section-by-section reference for this cycle</a>. Saved public snapshot: October 6, 2026. The local examples are fictional; use your own authentic evidence and the applicable official guide.</p>`;
    }
  };
})();
