module.exports = {
  'A-mission': `Riverview High's vision centers on an education shaped around individual learners so that graduates are ready to enter college, begin a career, or pursue both. Its mission identifies five responsibilities: (1) set ambitious expectations and offer demanding, standards-aligned learning connected to situations beyond school; (2) maintain a secure, personal learning setting with the relationships associated with a small school; (3) strengthen the knowledge and abilities of teachers and other staff to meet every student's needs; (4) connect students and families with community services that reduce barriers to learning; and (5) give educational partners meaningful influence and opportunities to participate in improvements to their school and surrounding community.`,
  A1: `I selected Chronic Absenteeism as the California indicator for this investigation. The opening table compares three reporting years for the entire school and several demographic groups. Across those years, the schoolwide rate at Riverview High averages approximately 35%, providing a reference point for examining differences among groups. The comparable averages are about 50% for English learners, 38% for socioeconomically disadvantaged students, and 45% for students with disabilities. Asian students have the lowest average, approximately 15%. The averages for African American, Filipino, and Hispanic students are approximately 51%, 23%, and 36%, respectively. These figures describe overlapping populations rather than separate portions of the student body.

Most groups show lower chronic absence rates by 2024-2025 than they did in 2022-2023. The year-to-year movements are not identical, however. English learners, Asian students, and African American students experienced an increase in the middle year, followed by some improvement in the final year. For English learners, the first-to-last-year comparison remains unfavorable even though their final-year rate is slightly lower than the previous year's. Comparing the rounded three-year averages gives a difference of roughly 15 percentage points between English learners and all students. I chose the English learner population for further inquiry because the disparity has continued and because the group represents approximately 166 students, a substantial part of this school. The annual figures also show that the schoolwide improvement has outpaced improvement for this group.

To investigate what might accompany this attendance pattern, I examined the School Experience Survey and the California Dashboard's English Learner Progress Indicator. These additional measures concern classroom experience, participation in school life, and language development. I selected them to explore possible explanations for the attendance difference, recognizing that a relationship between measures would need further investigation before it could be treated as a cause.

The Academic Focus item in the survey asks whether students experience their teachers' lessons as enjoyable. I considered this because a positive classroom experience may support a student's willingness to attend. Across the three years, approximately 49% of English learners responded favorably, compared with about 41% of students overall. English learners therefore reported more favorable experiences on this item than the schoolwide population. At the same time, the remaining approximately 51% prompted questions about students who may not experience that connection. The survey alone does not tell me whether those respondents are the students with frequent absences, and the nonpositive responses could include neutral views.

The school-climate item addresses participation in extracurricular activities. In secondary schools, athletics and clubs can give students additional reasons to attend: athletic eligibility may depend on attendance, while clubs involve responsibilities to peers and projects. I wanted to know whether English learners had comparable opportunities for these connections. Their average participation rate was approximately 40%, compared with 49% schoolwide. That difference raises a question about access to school activities and the sense of belonging those activities can provide. It may be relevant to attendance, but participation and attendance records would need to be examined together to establish who experiences both conditions.

Finally, I examined language development because missed instruction and academic progress can influence one another. The ELPI table shows that, on average, approximately 48% of English learners moved to a higher reported proficiency level. About half of the school's English learner population consists of newcomers. These students may be developing initial English skills while adjusting to a new culture, housing arrangements, and, in some cases, earlier traumatic experiences. I wondered whether the students not advancing a reported level were predominantly newcomers, although the aggregate figures cannot answer that question. Remaining at a level also does not necessarily mean that no learning occurred.

One possible explanation is that insufficient language support contributes to academic frustration, weakened engagement, and eventually absence. Another is that social, emotional, or economic circumstances interrupt attendance and thereby reduce opportunities to develop English. Both directions deserve attention. The relationship between attendance and achievement discussed by Liu and colleagues (2021) provides a reason to investigate these connections, but does not identify the explanation at Riverview. My working concern is that newcomers may face several of these challenges at once. I would need student-level attendance, language-development, and support information before concluding how much of the chronic absence pattern belongs to that subgroup.`,
  A2: `To understand English learners' attendance experiences from several positions, I interviewed an English language development teacher, a student with a history of chronic absence, a Pupil Services and Attendance counselor, and a parent who participates in the English Learner Advisory Committee. Each person could describe a different part of the student's relationship with school: instruction, placement, attendance support, or family access.

The ELD teacher is early in her career and teaches the newcomer course that begins the district's English learner instructional sequence. Newly enrolled students enter her classes throughout the year, sometimes more than two in an almost alternate-week pattern. She wants each arrival to feel included, but repeatedly introducing students and revisiting objectives interrupts the continuity of lessons. She also described irregular attendance among students already enrolled. Some miss class for vaccination appointments; others take part-time jobs when a parent is ill. Several are adjusting to unstable housing or difficult experiences in their countries of origin. Her account helped me see how circumstances outside the classroom can weaken continuity inside it. It also connects with Bryk, Gomez, and colleagues' discussion of the increasing complexity of heterogeneous classrooms (p. 62). The account suggests a systemic instructional challenge, not simply a question of one teacher's effort or competence.

The student I interviewed had recently been reclassified after previously being chronically absent. He explained that he missed much of the preceding year because he disliked his courses and relationships with teachers. Although he spoke English fluently, his English learner designation from public elementary school had remained in place through private middle school. On entering Riverview, he was assigned to ELD classes. He described feeling discouraged, depressed, and disconnected in that placement. The English learner coordinator subsequently helped him complete reclassification, and he entered mainstream English at the end of that year. He reported attending more consistently and enjoying both his classes and teachers afterward. His experience made timely reclassification and appropriate scheduling important questions for this inquiry. It does not establish that all English learners with frequent absences have the same placement problem.

The attendance counselor described how a parent's substance use and homelessness had affected one student's ability to reach school. The student and his parents were living in a vehicle. On some mornings he awoke in a different city, far from campus, because the family had moved overnight. After learning of the circumstances, the counselor contacted the child welfare agency, and the student subsequently entered foster care. The counselor used this example to explain how traumatic and unstable living circumstances can interfere with daily attendance and a student's connection to school. I understood it as an account of a serious access barrier, while recognizing that it does not indicate how many English learners experience that barrier.

The ELAC parent added a community transportation perspective. Two bus routes had formerly served the school area at roughly fifteen-minute intervals. Following a service change, families depended on one route with less frequent service and stops farther from some homes. Students sometimes faced long waits or could not board as expected. For families without the resources for private transportation, missing a bus could mean remaining home rather than walking three to five miles. This interview broadened my understanding of the conditions surrounding attendance. Taken together, the accounts suggest that instructional continuity, appropriate placement, housing stability, and transportation all merit examination. They offer distinct explanations to investigate rather than a single explanation that can be assumed to apply to every English learner.`,
  A3: `Three related concerns emerged when I compared the interviews. The first involved students' opportunities to develop English and progress through their courses. The newcomer teacher described frequent changes in class membership and repeated review that made instruction difficult to sustain. The wider concern was that some students continued to struggle with communication, reclassification, and other content courses after several years of ELD instruction. The ELPI figures add a related question: approximately 48% of English learners advanced a reported proficiency level on average across the three years. The remaining students cannot simply be described as learning nothing, because maintaining a reporting category may include growth within that category. Nevertheless, the combination of reported classroom interruptions and the progression figures makes instructional continuity worth examining.

A second concern was connection to school. Newcomers may find it difficult to build relationships when they cannot easily communicate with teachers or classmates. The recently reclassified student's account showed a different experience: feeling confined to an inappropriate placement despite speaking English fluently. His frustration and disengagement suggest that belonging can be affected by placement as well as by language access. The approximately 40% average extracurricular participation rate for English learners provides another reason to ask how students become involved in school life. It does not establish that the interviewed student, newcomers, and nonparticipants are the same students.

The third concern involved material conditions outside school. The attendance counselor described housing instability, while the ELAC parent explained reduced access to public transportation. Both accounts point to difficulties reaching campus, regardless of a student's interest in learning. Students managing these circumstances may have to prioritize immediate family needs and basic stability. The roughly 50% average chronic absence rate among English learners makes these accounts relevant to the inquiry, but it does not quantify how common each barrier is. Together, the three concerns connect language-learning opportunities, belonging, and access to attendance. They also show why an explanation based entirely on student motivation would leave important parts of the evidence unaddressed.`,
  A4: `The equity concern at Riverview High is the sustained difference in chronic absenteeism between English learners and the school as a whole. Over the three reporting years, the rounded averages are approximately 50% and 35%, respectively, a difference of about 15 percentage points. This pattern calls for examining whether the supports available to English learners fit the different circumstances within that population.

Finn and colleagues (2023) discuss the importance of considering long-term English learners and newcomers separately when studying secondary-school attendance. In addition to common reasons for missing school, such as illness, moving, or reduced academic motivation, attendance may reflect a mismatch between students' needs and the services they receive. The interview accounts make that distinction useful here. Newcomers may need help understanding instruction while also adjusting to a new country, limited family income, or housing insecurity. Language access and connections to social services could both matter to their ability to attend regularly.

Long-term English learners may face a different set of concerns. The student interview raises questions about reclassification support and course placement. When students remain in language-development courses that they experience as inappropriate, their schedules can also restrict elective choices or participation in athletics. Taking two English periods each year may reduce access to the parts of school they find most engaging. These are potential mechanisms to investigate, rather than effects established for the entire group by one interview.

The research discussion of reclassification is relevant because students designated as fluent English proficient generally enter a more mainstream educational program and may encounter fewer forms of tracking, labeling, and exclusion associated with continued English learner designation. Carlson and colleagues (2016) are cited in that discussion of academic outcomes, while the source also acknowledges that findings are not uniformly positive. This literature helps frame questions about services; it does not supply a local estimate of their effect on attendance. The two broad directions for further inquiry are therefore newcomer access to instruction and social support, and long-term English learners' access to appropriate reclassification and programming. Sustained systems would need to respond to both, with local evidence showing which students need which forms of assistance.`,
  A5: `Riverview's vision commits the school to an individualized education that prepares students for college, careers, or both. The English learner experiences described in this inquiry raise questions about how fully that commitment is realized. Under the district's newer programming policy, placement follows grade level rather than language proficiency. That arrangement may make it harder to match ELD instruction to individual needs. Reclassification assistance also needs examination for whether it responds to the particular requirements each student has yet to meet.

Students who speak English fluently but remain classified as English learners may experience their assigned courses as limiting. The student interview illustrates how that frustration can be associated with disengagement and absence. Newcomers face a different concern: after several years of high school, limited English proficiency or uncertainty about college readiness may lead them to question the value of completing school and to consider other future options. These possibilities connect directly to the mission's emphasis on a secure, personal, small-school learning environment that addresses academic and social-emotional needs.

The attendance disparity remained across the three years despite existing school systems. That persistence warrants reviewing how individualized support reaches English learners, but it does not by itself demonstrate that every service had no effect. The school needs to examine what was offered, who received it, and whether the support matched different subgroup circumstances. A more coordinated approach to placement, reclassification, and attendance assistance would help the school assess its progress toward the mission. The central comparison is between the promised individualized experience and the instructional and access difficulties reported by students, staff, and families.`,
  B1: `The Step 1 analysis identified a continuing attendance disparity for English learners at Riverview High. Their rounded three-year chronic absence rate is approximately 50%, compared with 35% for the school overall. This difference of about 15 percentage points led me to consider three possible contributing conditions, using both the numerical evidence and the interviews. I distinguish conditions suggested by the evidence from causes that would require further verification.

The first possible factor is structural: newcomers may not have consistent access to demanding instruction that is appropriately supported for their language development. The ELD teacher described limited preparation for the newcomer course and difficulty maintaining a coherent pace while students enter throughout the year. Frequent arrivals require her to revisit content and welcome new learners while continuing instruction for students already present. Her relative inexperience and the demands of the enrollment pattern may affect the learning opportunities available in that classroom. The ELPI figures, with about 48% of English learners advancing a reported level on average, provide a related reason to examine instructional support. They do not measure this teacher's competence or establish that the students maintaining a level made no progress. My concern is that limited access to English can also make other courses difficult, leading students to fall behind in credits. Academic frustration may then weaken their connection to school or make employment seem more immediately worthwhile than continuing their education.

The second possible factor concerns an institutional decision: the revised district English learner course-placement policy. The former long-term English learner course supplemented secondary English language arts and supported English-fluent students in meeting reclassification requirements. That course was removed, and students are now assigned to ELD courses by grade rather than by proficiency. The resulting classrooms include a wider range of language needs. Some students may interpret work below their perceived proficiency as a remedial placement and feel that the school underestimates their abilities. The recently reclassified student described precisely that reaction. He associated his ELD assignment with feeling unintelligent, reduced self-esteem, disengagement, and frequent absence. The survey's approximately 49% favorable average on enjoyable learning raises a related question about classroom experience, although the other 51% cannot be assumed to be the students who are absent. His account supports examining the placement process and differentiated instruction rather than generalizing his experience to everyone.

The third possible factor is structural access to school, particularly housing instability and unreliable public transportation. The attendance counselor described newly arrived students whose families face unstable employment and difficult family relationships. In the example she shared, homelessness made reaching campus unpredictable. Such experiences can interrupt attendance and make it difficult to sustain relationships with classmates or continuity in coursework. The ELAC parent described a separate but related barrier: fewer bus routes, less frequent service, and stops farther from some homes. Students unable to arrange another ride may remain home after a missed or delayed bus.

These access conditions also raise questions about participation beyond the school day. English learners reported extracurricular participation averaging about 40%, compared with 49% for students overall. Students who must leave immediately to secure transportation, or who are absent altogether, may have fewer opportunities to join clubs and sports. However, the survey does not reveal the reason for each student's nonparticipation. Together, the three possible factors concern instructional access, placement and reclassification, and the practical ability to attend and participate. They suggest where the school could investigate its systems, while leaving open how strongly each condition contributes to the overall attendance disparity.`,
  B2: `The institutional and structural conditions identified in the inquiry may affect both learning and well-being. They offer possible explanations for the approximately 15-percentage-point difference in the rounded chronic absence averages, but their individual effects have not been measured. The first concern is newcomers' access to instruction that helps them develop English while completing the rest of their education. Students who still struggle with the language after two years of ELD may find graduation courses increasingly difficult and may need to recover credits from earlier failures. Difficulty in English therefore extends beyond language-development classes into other subject areas. Repeated academic frustration can reduce confidence and make regular attendance seem less worthwhile.

The second concern is the newer placement policy and the instructional preparation accompanying it. Teachers had limited time to prepare for classes containing students at very different proficiency levels. Without sufficiently differentiated tasks and language supports, instruction appropriate for some students may leave others either overwhelmed or insufficiently challenged. Students may also miss targeted assistance with the particular reclassification criteria they have not met. Feeling misplaced or overlooked can affect self-esteem and belonging. The student's account connects this experience with disengagement, although it remains an individual account rather than evidence of the policy's effect on every English learner.

The third concern involves housing and transportation. Uncertainty about where to sleep or whether there will be enough food can make immediate survival more pressing than school assignments. These circumstances may bring substantial stress and interrupt routines that support learning. Unpredictable bus service creates a different daily burden: students may not know whether they will arrive on time or be able to reach campus at all. Repeated travel difficulties can increase anxiety and make staying home seem easier than attempting the journey.

The combined concerns are therefore academic, social, and emotional. Language barriers can limit success in several courses; inappropriate placement can undermine confidence; and economic instability can prevent attendance regardless of motivation. These conditions may reinforce one another, weakening students' sense that they belong and can succeed at school. Understanding their effects requires attention to what students report, what support they actually receive, and how their attendance and learning develop over time. The evidence establishes an ongoing disparity and reasons to investigate these pathways, rather than a measured causal contribution from each factor.`,
  B3: `The research considered in this inquiry provides context for the three possible contributing factors. For instructional access, Santibanez and Gandara (2018), drawing on Rueda and Stillman (2012), describe preparing teachers for increasingly diverse classrooms as a longstanding challenge. They emphasize the particular demands of secondary schooling: English learners face complex academic content and language expectations while having relatively little time to acquire the skills needed for graduation. This is relevant to newcomers at Riverview, who may expect to learn English quickly enough to participate fully in their new school. The teacher's account of frequent enrollment and interrupted pacing makes preparation and instructional support worth examining. The research does not establish that this particular teacher lacks competence, but it clarifies why the demands of her assignment matter. When language development and coursework become difficult together, students may become discouraged and their connection to school may weaken.

A second line of research concerns placement and access to academic content. Callahan and colleagues (2010), discussing earlier work by Harklau, Linquanti, and MacSwan and Rolstad, explain how English learner placement can delay access to subject matter until students are judged sufficiently proficient. Students can then be expected to succeed in content they had fewer opportunities to study while learning English. That problem is relevant to the student interviewed here. His English learner designation continued through private middle school, and he entered high school without having completed reclassification. He described being distressed by an ELD assignment despite speaking English fluently. The extra English period felt restrictive, and he associated the placement with reduced self-confidence, disengagement, and absence. The literature helps explain why placement deserves examination, while his account identifies a local experience rather than demonstrating the district policy's overall effect.

The third research connection concerns socioeconomic conditions. Santibanez, Gottfried, and Freeman (2024), referencing Attendance Works and Everyone Graduates Center (2017), discuss circumstances associated with absence among English-classified students. These include poverty, food insecurity, health concerns, transportation difficulties, limited adult supervision, and responsibilities such as caring for siblings or other relatives. Older students may be especially likely to miss school because of family obligations. Riverview serves a low-income immigrant community, and the scenario identifies approximately 30% of its overall enrollment as living in poverty. The counselor's and parent's interviews offer local examples of housing and transportation barriers consistent with that broader discussion. The alignment supports further inquiry but does not tell us how many local absences arise from each circumstance.

The National Center for Homeless Education (2022) also draws attention to students whose homelessness and chronic absence overlap. Its reporting identifies unaccompanied students as approximately 9% of students experiencing homelessness in each year since 2015-2016, and migratory students as approximately 1% since at least 2014-2015. It also describes small annual increases, no greater than one percentage point, in the English learner share of students experiencing homelessness between 2014-2015 and 2017-2018. These figures concern reported populations and should not be treated as estimates for Riverview.

Newcomer enrollment at the school changes in response to social conditions beyond the school's control. The practical implication is to establish a welcoming reception and a reliable connection to assistance as soon as students enroll. Students facing unstable circumstances need to know which adults they can approach and whether school is a dependable place to seek help. Across the three research connections, I see reasons to examine instructional preparation, placement, and access supports together. I would use local evidence to determine how these broader findings apply to particular students and to avoid assuming that a published association proves the cause of the school's attendance gap.`,
  B4: `Addressing the attendance disparity requires school supports that respond to the instructional, institutional, and access conditions identified in the inquiry. I propose four connected areas of need.

First, Riverview needs a committed group of ELD teachers who want to develop their practice with English learners. This professional learning community would study research-informed differentiation, scaffolding, and culturally and linguistically responsive teaching. Peer mentors, instructional coaches, and the bilingual program coordinator could guide that learning. The intended benefit is more consistent access to meaningful instruction, helping students experience academic success and see value in attending school regularly.

Second, students need focused reclassification assistance. The English learner coordinator or an instructional coach could use ELPAC domain results to identify the specific skills keeping students from meeting the criteria. A Tier 2 pull-out program would provide small-group support once or twice weekly during the semester before the spring assessment. This would give long-term English learners a clearer path toward reclassification and show that adults are attending to their individual progress.

Third, the school needs culturally and linguistically relevant extended-learning experiences. Visits to locations around students' new city could provide opportunities to develop English through social interaction outside formal classroom tasks. Such experiences would broaden learning, create enjoyable shared activities, and strengthen students' participation in school life.

Finally, attendance counselors need support to organize intervention teams. Teachers, academic counselors, school-climate advocates, parent volunteers, and administrators could each take responsibility for particular students with frequent absences. Team members would contact home when a student is absent, welcome the student back, and hold conversations that build trust and reveal barriers. They would also connect students with resources suited to those circumstances. Together, these actions would make attendance support more personal and continuous. Their effectiveness would need to be monitored through both implementation records and student outcomes, with attention to whether the intended assistance actually reaches the students who need it.`,
  B5: `My equity analysis identified a persistent difference on the chronic absenteeism indicator at Riverview High. English learners averaged approximately 50% across the three years, compared with approximately 35% for the overall school population. The rounded difference is about 15 percentage points. Interviews added several concerns to the numerical pattern: the continuity of English language instruction, students' connection to school, and the effects of difficult socioeconomic circumstances. These findings give the attendance disparity a more specific local context, while leaving questions about the extent and contribution of each condition.

The analysis suggests three areas for action. Newcomers need dependable access to instruction that supports language development and challenging academic work. Long-term English learners need appropriate placement and assistance with reclassification under the revised district policy. Students facing housing or transportation difficulties need practical and relational support that makes attendance possible. The persistence of the gap indicates an unresolved problem; it does not, by itself, establish that every existing school response has failed. School records and student experiences would be needed to determine which services have reached whom.

English learners need educators who are willing to strengthen their professional knowledge and invest in their achievement. Improved instructional support should help students develop language, participate in other subjects, and experience pride in belonging to a school that takes their learning seriously. They also need adults who will organize targeted reclassification assistance early in high school. The requirements become more demanding in the upper grades, making ninth- and tenth-grade support especially relevant. Earlier progress may help students avoid feeling trapped in a program and give them a clearer reason to continue toward a diploma.

Students with repeated absences also need a trusted adult who checks on their well-being, communicates with family, and helps set achievable goals. Balfanz and Byrnes' 2013 study on combating chronic absenteeism discusses quality mentoring within a schoolwide effort as a promising attendance and achievement strategy. That research supports considering mentoring here, while local evidence would be necessary to judge its results. The concern is that students' difficulties can remain unnoticed when monitoring, relationships, and intervention responsibilities are fragmented.

The proposed response therefore has several linked components. An ELD teacher group would pursue professional learning suited to the range of language needs in its classrooms. A Tier 2 pull-out program would provide intensive, individualized assistance with the reclassification skills that students still need to demonstrate. Extended-learning opportunities would create social settings for using English and connecting with school. A designated group of staff mentors would maintain contact with students who are chronically absent and help them obtain appropriate support. These actions respond to the identified needs rather than treating attendance as a matter of reminders alone.

The proposal fits several existing resources in Riverview's context. A bilingual coordinator could organize professional learning for interested ELD teachers. A part-time intervention coordinator could work with that coordinator to design and operate the Tier 2 program. The school also has three attendance counselors who commonly supervise five or more interns. They could organize mentoring and recruit willing school personnel to participate. This staffing makes the proposal plausible, although schedules, responsibilities, and available time would still need agreement before implementation. The work would require coordination among people whose roles already touch different parts of the problem.

My problem statement is that English learners experience a sustained attendance disparity while instructional, placement, and access supports may not consistently match their varied needs. The school needs a coordinated, individualized response that strengthens teaching, advances reclassification, creates meaningful participation, and connects students with trusted adults. These changes align with the school's commitment to a personalized education that prepares each student for the future. The intended outcome is a reduction in the chronic absence difference, with evidence collected to determine whether the proposed supports are implemented, who benefits, and what needs revision. Closing the gap remains a goal to evaluate rather than a result that can be promised in advance.`,
  C1: `The attendance analysis shows a rounded three-year average chronic absence rate of approximately 50% for English learners and 35% for all students at Riverview High. I selected two strategies that respond to the resulting disparity of about 15 percentage points and can draw on resources already present at the school. One addresses classroom learning opportunities; the other addresses personal connections and access to assistance.

The first strategy is an ELD teacher learning group focused on strengthening instruction. It responds to the possible structural factor involving newcomers' access to challenging, well-supported learning. The language-progress figures, including the approximately 48% average advancing a reported level, led me to examine instructional opportunities alongside attendance. That figure does not mean that everyone else made no progress, but it reinforces the need to understand how students are supported. When students struggle in courses and accumulate missing graduation credits, frustration may contribute to disengagement. The proposed group would help teachers examine that concern through their own practice.

The bilingual coordinator would lead meetings twice each month during the fall and once each month in the spring. Before and between meetings, the coordinator would assemble resources on specially designed academic instruction in English, culturally and linguistically responsive pedagogy, and translanguaging. These materials would guide collaborative planning rather than function only as a reading list. Teachers would establish an instructional goal, select a strategy, and use it with students before the next meeting. They would then bring evidence of engagement and learning to discuss what happened.

The group would also examine attendance and academic information to consider how classroom conditions respond to different learners. Its inquiry would follow a recurring plan, implementation, study, and adjustment process: decide what to try, use it, evaluate the evidence, and share the findings. I would first present the proposal to the principal for approval and then introduce it at an ELD department meeting to recruit interested teachers. The purpose is to build professional capacity and improve the quality of students' daily experience. More meaningful instruction may strengthen engagement and attendance, but those outcomes would need to be checked rather than assumed.

The second strategy is a mentoring program with regular well-being check-ins for students who are chronically absent. It responds to the housing and transportation barriers described in the qualitative evidence. A dependable adult relationship could strengthen contact with families, help students feel connected to campus, and make it easier to identify a problem before it repeatedly interrupts attendance. The program would combine relationship-building with access to practical resources.

An attendance counselor would lead the program and introduce it at the monthly meeting of staff whose assignments are outside the classroom. The counselor would present the attendance evidence, identify students needing individualized intervention, and explain the responsibilities and intended outcomes. Volunteers would each be matched with one student. A one-page conversation guide would help mentors ask about well-being, attendance, and barriers, while the counselor would remain available to coordinate school and community services.

Mentors would meet as a group once a month throughout the school year. They would report progress or continuing difficulty, raise questions, and seek help with concerns beyond their roles. Their conversations with students could reveal housing, transportation, or other needs that are not visible in an attendance percentage. Connecting students and families with suitable assistance could reduce some of the stressors that interfere with participation. Together, the two strategies address the problem statement through stronger instruction and more individualized support. Their implementation would need to be documented so the school can distinguish the intended benefits from changes actually observed.`,
  C2: `The proposed ELD teacher group addresses the problem statement by investing in the educators who work with English learners every day. Under the bilingual coordinator's guidance, teachers would study and practice ways to organize classrooms, build relationships, scaffold tasks, and differentiate instruction. These everyday choices communicate whether students' needs are recognized. When the classroom experience is responsive, students may be more likely to feel that they belong and that their education matters. When it is not, frustration can add to an existing pattern of disengagement.

Strengthening teacher preparation is a concern beyond Riverview. Santibanez and Gandara (2018) examine the limited availability of teachers fully authorized to teach English learners and discuss teachers' expressed need for coaching, observing colleagues, and collaborative professional learning. That finding supports the proposed combination of shared planning, practice, and review. A teacher group could provide more sustained assistance than isolated presentations because members would examine what happens when they apply a strategy. The intended result is improved instruction, with increased engagement and attendance as outcomes to investigate. The research does not guarantee those outcomes for this school.

The mentoring and well-being program addresses a different part of the problem. Riverview has coordinators, counselors, itinerant staff, and assistant principals whose work could support a targeted Tier 3 intervention under an attendance counselor's leadership. Matching these adults with individual students would use existing staff relationships and knowledge. Students facing traumatic or unstable circumstances could have someone who notices their absence, listens to their concerns, and encourages them through difficult days.

Mentors could also identify family needs early enough for the school to arrange timely help. A trusting relationship may reveal a transportation, safety, or housing concern that a formal attendance notice does not uncover. The counselor would coordinate the appropriate resources, while the mentor maintains the personal connection. This combines emotional support with practical assistance rather than expecting encouragement alone to remove barriers.

Balfanz and Byrnes' New York City study (2013) provides a relevant research connection. In the quarter of participating schools showing the strongest effects, chronically absent students supported by Success Mentors gained more than a month of attendance on average. That result is specific to those schools and should not be presented as the expected gain at Riverview. It nevertheless supports investigating a coordinated mentoring approach. My rationale is that students may be more willing and able to continue attending when adults respond to their circumstances and help them access support. Local attendance records and implementation evidence would show whether the proposed relationships are contributing to that goal.`,
  C3: `The ELD teacher learning group responds to the first proposed contributing factor: inconsistent access to instruction that meets newcomers' language and academic needs. Its immediate goal is to strengthen teaching so students can engage with demanding content and experience progress. A more positive learning experience may support reengagement and attendance. The equity analysis supplied several reasons to consider this approach, including the language-progress pattern and the survey average showing that approximately 49% of English learners regarded classroom learning as enjoyable. These measures raise questions about instruction and experience, but do not establish that students who answered differently are choosing employment or family duties instead of school.

The interviews add more specific context. The newcomer teacher described the difficulty of sustaining lessons while new students enter throughout the year. The student described an ELD placement that he experienced as inappropriate and discouraging. Both accounts suggest areas for professional learning: planning for changing enrollment, differentiating tasks, and understanding students' perceptions of placement. They do not support attributing the entire attendance disparity to teachers. The proposed group would give teachers a way to examine those conditions together and test responses in their classrooms.

This strategy aligns with the mission's commitment to developing staff capacity to serve all students. Collaborative study and review of classroom evidence would make that commitment concrete for English learners. The group would also support individualized learning by asking teachers to consider differences in language proficiency and educational experience. The expected attendance benefit follows from an improved daily learning experience, but the school would need evidence to determine whether that benefit occurs.

The mentoring program responds to the third proposed contributing factor: socioeconomic conditions that interfere with attendance. Its immediate goal is a consistent relationship through which students feel recognized and can obtain help. The counselor's housing account and the parent's transportation account identify barriers that cannot be resolved simply by telling students to attend more often. A mentor could learn about the specific difficulty, communicate with the family, and coordinate assistance through the attendance counselor.

The extracurricular survey provides another question about connection to school. English learners' participation averaged about 40%, suggesting that many were not engaged in those activities. Students uncertain about where they will sleep or how they will get home may have limited ability to remain for clubs or sports. The survey alone does not identify those circumstances, but the interviews explain why access deserves attention. Mentoring could help students explore available activities while also addressing the conditions that make participation difficult.

The program connects with the vision of an individualized education leading toward college and career readiness. Each mentor would attend to one student's academic and personal circumstances rather than provide the same response to every absence. This is a practical expression of the school's stated commitment. Across both strategies, the connection to school goals is therefore specific: develop educators' capacity to improve learning, and provide personal support that helps students participate. The school would assess those commitments through the services delivered and the experiences and outcomes of the students involved.`,
  C4: `In the first feedback round, I met with Riverview's principal. I sought his perspective because he had worked with the attendance counselors for two years on reducing chronic absence. He responded favorably to both proposals and suggested ways to make each more useful within the school.

For the ELD teacher group, he recommended using ELPAC domain results to identify the language skills most in need of support. He also wanted the work to influence instruction beyond ELD classrooms. He suggested that participants collect evidence of the strategies they use and the results they observe, then present that work to the entire faculty at the end of the year. Such a presentation could encourage teachers in other content areas to form a similar group or adopt useful practices. His feedback shifted the proposal toward both targeted planning and wider sharing of classroom evidence.

For mentoring, the principal recommended adding questions about sports and clubs to the check-in guide. Discussing students' interests could connect them with additional trusted adults and create more reasons to participate in campus life. The intention was to expand belonging through relationships and activities rather than limit every conversation to absence.

I made several changes after this meeting. For the instructional group, I planned for the bilingual coordinator to have the access needed to create a group within the school's learning management system. That shared space would hold resources, lesson plans, and materials developed or used by participants. Other faculty members could be invited to explore the collection, and faculty meetings could draw attention to it. This would make the group's work accessible across departments and support broader use of language-development strategies. The principal's recommendation about domain-level evidence would also inform the group's instructional priorities.

For mentoring, I planned to prepare a directory of clubs with meeting times and locations, together with a sports list showing seasons and coach contact information. Mentors could use these resources while discussing a student's interests. Having the information available would make it easier to turn a conversation about belonging into a specific connection on campus.

In the second feedback round, I shared the revised proposals with an attendance counselor. The counselor noted that students facing economic hardship often think about finding work. She recommended that the ELD group regularly connect learning with workplace skills so students can recognize its practical value. In response, I planned to involve the work-based learning coordinator. That coordinator could arrange guest speakers or field trips connected to skills and topics teachers were addressing. This addition would help relate classroom learning to future opportunities without assuming that all students have the same plans.

The counselor also raised a recruitment concern for mentoring. Staff outside classroom assignments may be reluctant to give up work time, particularly when a new program's demands are uncertain. She suggested inviting classroom teachers as well, with training and resources to mentor one of their own students. I therefore added a faculty-wide presentation in which the counselor and I would share the English learner attendance evidence, explain the mentoring responsibilities, and invite teachers to volunteer. This broadened the potential mentor pool and made the support structure clearer. Across the two rounds, the feedback changed instructional priorities, resource sharing, activity connections, work-related learning opportunities, and recruitment. These were concrete revisions to the proposals, while staffing and implementation arrangements would still need to be confirmed.`,
  C5: `Successful implementation would require participation from teachers, staff with support assignments, families, and students. I would use the attendance evidence to explain the concern and describe how each proposed strategy responds to it. Communication would need to make both the purpose and the responsibilities understandable so that participation rests on a shared view of the work.

To recruit ELD teachers, the bilingual coordinator and I would attend an English department meeting. We would present the chronic absence disparity, explain the possible instructional contributing factor, and describe the teacher group's goals and meeting expectations. The invitation would emphasize equitable opportunities for English learners and ask interested teachers to commit to collaborative learning. For mentoring, the attendance counselor and I would present the same attendance concern at a faculty meeting, explain the check-in responsibilities and available support, and invite volunteers from across the school.

I would also seek the participation of the bilingual coordinator and attendance counselors as program leaders. Offering to share leadership would help distribute planning and follow-up responsibilities. We would agree together on how to organize the work and connect it with the school's commitments to individualized education and staff development. These activities fit aspects of their existing roles, but competing responsibilities and limited time may have prevented similar work from developing. Shared planning could make the proposals more feasible, although the actual time available would need to be established rather than presumed.

For families, the bilingual coordinator, attendance counselor, and I would arrange an after-school meeting for parents of students in ELD. Invitations would include mailed letters, flyers sent home, and a principal's telephone and email message. A light dinner would be offered. At the meeting, we would explain the attendance figures, discuss the value of consistent participation, and introduce the instructional group and mentoring program. We would ask families to support attendance while also listening to the barriers that make it difficult. That exchange would help distinguish a need for information from a need for practical assistance.

For students, I would introduce myself during ELD classes and explain that I would return to learn about their classroom experiences. Regular visits would communicate continuing interest in their education. I would make a point of recognizing students with previous attendance difficulties when they are present and encouraging their return. For mentees, I would seek funding for tangible recognition when they reach and sustain agreed attendance goals. Possible incentives include a breakfast treat, a pizza lunch, movie tickets, or school merchandise. Such recognition would accompany personal support rather than replace attention to barriers beyond students' control.

Several implementation difficulties are foreseeable. Initial enthusiasm may fade without regular follow-up, clear responsibilities, and recognition of participants' efforts. Teachers and mentors may carry out the work unevenly, creating different experiences for students. Staff who already feel overextended may withdraw. The leaders would therefore need to monitor participation and workload, provide support, and discuss inconsistencies before they become established patterns. A collaborative approach should make those concerns visible rather than assume that volunteering guarantees sustained implementation.

The possible benefits include more consistent attendance, stronger family communication, and better access to school and community resources. Regular examination of evidence could also strengthen decision-making across the school. Recognition events and shared celebrations may help English learners feel that their participation is valued. Coordinating school, home, and community efforts could create a more dependable support network. These benefits remain intended outcomes, and the school would need to review both implementation and student experiences to determine whether they occur. Clear communication, shared responsibility, and attention to the practical demands of participation are central to building lasting support for the two strategies.`,
  D1: `I chose Riverview's principal as a feedback partner because of his experience with instructional improvement and attendance interventions. He had been at the school for two years, and I had observed him use his broader educational experience when guiding structural changes. I trusted his judgment and wanted to understand how my proposals fit both the school's needs and the expectations of the district and state. His approach also provided a model of leadership that keeps student needs visible while involving colleagues in decisions.

Our conversations broadened my understanding of how to build support for change. He endorsed the ELD teacher group in part because it allows teachers to exercise professional judgment while developing their capacity. That helped me see the importance of inviting teachers into a shared inquiry. People may be more willing to participate when they can influence the work and understand its purpose. His recommendation to use ELPAC domain evidence made that purpose more concrete: the group could identify a learning need, select an instructional response, and examine a measurable result. Evidence would help explain why the work is worthwhile rather than leave it appearing to be an additional task based on one person's preference.

His suggestion about clubs and sports also changed my thinking. The extracurricular survey had raised a question about connection to school, and he showed how mentoring conversations could explore that question with individual students. Asking about interests could connect a student with additional adults and activities while helping the mentor understand what participation means to that student. This reminded me that numerical patterns become more useful when they guide conversations, and that keeping students' experiences central can help educational partners see the value of a proposal.

I selected the attendance counselor because she works directly with students who are chronically absent and with families experiencing economic hardship. I wanted her judgment about feasibility, not only agreement with the general ideas. Across her career she had implemented both collaboratively developed interventions and district-directed programs. That experience gave her insight into the conditions that encourage or limit staff participation.

Her advice to connect ELD lessons with workplace skills led me to recognize the work-based learning coordinator as an additional resource. Teachers could receive help arranging speakers or experiences that make the practical value of learning more visible. This connection could strengthen participation in the teacher group because members would have another colleague supporting their efforts. It also widened my view of the resources already available at Riverview.

For mentoring, the counselor anticipated that staff outside classroom assignments might not have time or willingness to participate. Her suggestion to include classroom teachers changed my recruitment plan. The counselor and I would present the attendance evidence and mentoring structure to the entire faculty, explain the support volunteers would receive, and invite broader participation. I learned that building support can involve changing who is invited, not merely improving the explanation given to the original group. Taken together, the two feedback partners helped me connect evidence, professional autonomy, practical resources, and shared responsibility. Their contributions made the proposals more specific and helped me think about participation as something developed through collaboration rather than secured through an announcement.`,
  D2: `This cycle changed the way I approach improvement work. At the beginning, I tended to move quickly from a problem to an interpretation or a proposed solution. Collecting evidence, reading about improvement, and reflecting at each step helped me slow that process. I began to ask what I still needed to understand about the school's social and cultural setting before deciding what should change. Listening to other people made the problem more complex, but it also made my thinking more responsive to the students and adults involved. I now see that an equity focus requires attention to how a system operates, whose experiences are represented, and whose needs may remain less visible.

During Step 1, I learned to use several sources to develop an understanding of a student population. The attendance figures established a pattern that needed explanation. They did not supply the experiences behind the pattern. Looking carefully at the numbers helped me decide what to ask in interviews and whose perspectives could contribute. Rather than gather qualitative information without a purpose, I tried to use it to investigate questions the numerical evidence left unresolved. This required planning questions that were relevant to each person's role and sensitive to the circumstances they described. The teacher, student, counselor, and parent helped me see different aspects of the same attendance concern.

This process also changed how I think about the responsibilities of a principal. Examining equity differences should be a recurring part of leadership, not an activity completed only for one project. A leader needs to understand students' progress and the school systems that support or interrupt it. Conversations with teachers, students, and families can help interpret numerical patterns, while those patterns can suggest useful questions for future conversations. In a principal role, I would therefore pay close attention to the concerns and proposals people bring forward. They may reveal conditions that are not apparent in a report. I would use that information to build collaborative responses and to revisit whether those responses are working.

Step 2 helped me think more carefully about institutional and structural conditions. I needed to distinguish long-established expectations, beliefs, and practices from the arrangements and resources through which work is organized. Riverview has relatively little staff turnover, and some ways of working have become familiar over many years. I began to consider whether those routines could make certain English learner needs less visible. That possibility should be examined with evidence rather than treated as a conclusion about colleagues' intentions. It also means that improvement may require people to reconsider familiar assumptions together. Understanding the school's structures helped me identify resources that could support a feasible response, while understanding its institutional culture helped me anticipate the work involved in gaining participation.

The course reading that most directly challenged my habits was Bryk and colleagues' Learning to Improve (2015). Their discussion of moving prematurely to solutions helped me recognize a tendency in my own practice. Experience can make a proposed answer come to mind quickly, but familiarity with a problem does not establish that I understand its current form. I need a disciplined pause between noticing a concern and recommending an intervention. The equity analysis gave me practice in that pause: examine the pattern, ask what is uncertain, seek relevant perspectives, and reconsider the explanation. I want evidence-driven inquiry to become a routine part of how I work rather than an additional step I use only when time permits.

In Step 3, I used a fishbone diagram to organize possible contributing factors. Seeing the factors together helped me consider the wider system rather than focus on a single explanation. The diagram did not prove that each proposed factor caused the gap; it helped me identify relationships that deserved attention. From that analysis, I selected two strategies suited to the school's context: collaborative learning for ELD teachers and individualized mentoring for students with frequent absences. I considered the available personnel, the practical demands of implementation, and research relevant to each approach. This made the proposals more grounded than an immediate response based only on the attendance percentage.

Feedback from the principal and attendance counselor showed me that an equity-oriented leader must be willing to revise a proposal. Their contributions changed the instructional focus, the resources available to teachers, the mentoring conversation guide, and the recruitment plan. Sharing an idea transparently and allowing others to influence it can strengthen both the idea and participation in carrying it out. I intend to continue practicing these skills through improvement cycles in my current role. My aim is to keep students' needs central, use evidence carefully, remain open while collecting accounts, and use decision processes that give educational partners a meaningful voice.

I also learned more about my own strengths and limitations. One important realization was how much I rely on prior knowledge when I encounter a problem. Watching the principal respond to everyday school concerns helped me notice a different approach. I paid attention to his choice of language, his effort to remain neutral, and the way he made decision-making visible to others. Because Riverview is a pilot school, democratic participation is especially important to its leadership. I began considering how I could practice those habits now, rather than wait until I hold an administrative position. Observing a colleague's response gave me a concrete way to examine my own.

I see analysis, critical thinking, and collaboration as strengths I can build on. The proposals reflect my belief that school improvement depends on people working across classrooms and offices. My experience allows me to contribute ideas and help colleagues develop capacity, while I also need to remain willing to learn from perspectives different from mine. The principal and counselor demonstrated how quickly a proposal can improve when another person notices a resource, a constraint, or a student need I had overlooked. Those exchanges reinforced my commitment to shared work. At the same time, describing myself as a strong analyst is not enough; I need to check my interpretations, especially when separate percentages or individual accounts tempt me to make broader claims.

After learning this inquiry process, I would like to examine other state indicators for English learners, including graduation, college and career readiness, and SBAC proficiency at Riverview. If those analyses reveal further differences, I would bring the findings to the Governance Council so an appropriate committee could investigate them. I would participate in the committee's work and invite additional educational partners whose perspectives are relevant. The purpose would be shared responsibility for understanding the concern and developing a response, not simply presenting a finished solution for approval. This could help keep English learner needs visible across the school's improvement work.

My growth areas follow directly from these experiences. I need to continue interrupting the habit of deciding too soon, and I need a deeper understanding of existing school systems before recommending replacements or additions. Colleagues may already be doing work that I have not yet seen. Recognizing that work is necessary both for an accurate analysis and for respectful collaboration. I have begun attending Governance Council and School Culture Committee meetings to learn how decisions are made and who is involved. Those meetings give me opportunities to observe, contribute, and develop a more informed leadership approach. The cycle has shown me that understanding school culture and context is not background preparation; it is part of the work of identifying an equity concern and deciding how to address it.`,
  D3: `One professional learning goal is to apply the attendance equity-analysis process to other student populations at Riverview, including students experiencing homelessness, youth in foster care, Black students, and students with disabilities. I want to understand whether the proposed instructional and mentoring supports fit their circumstances or whether different contributing conditions call for other responses. Comparing these inquiries could deepen my understanding of the school's systems while keeping the mission's commitment to individualized education in view. I would be looking for both shared patterns and meaningful differences, rather than assume that one strategy serves every group in the same way.

A second goal is to seek a position on the Governance Council. Participating as a voting member would give me closer experience with the institutional issues the school faces and the processes used to address them. I would learn through discussions with colleagues, the consideration of competing perspectives, and the work of reaching agreement. This would help me develop a more democratic leadership approach and a stronger understanding of how support for a decision is built. It would also give me repeated opportunities to listen before proposing an answer, a habit I identified as needing further development during this cycle. These experiences would be directly relevant to a future administrative role.

My third goal is to lead an improvement cycle within my current coordination responsibilities. I am responsible for a committee implementing a community-school plan and deciding how its budget will support that work. Although I am not an administrator, leading this schoolwide effort requires the critical thinking, collaborative planning, and participation-building skills practiced in Cycle 1. It provides an immediate setting in which to continue developing them.

I would begin by creating a meeting timeline for the remainder of the year. The schedule would take account of deadlines for reviewing survey information, setting implementation goals, and reflecting on results before the year ends. From that timeline, I would identify monthly objectives and prepare agendas that specify the decisions or measurable products needed at each meeting. I would arrive with the data, materials, and background information members need to make informed choices.

Each meeting would close with individual and shared next steps, and the following meeting would include a report on what happened. Afterward, I would review whether our actions still align with the implementation plan and revise the next agenda when necessary. At the end of the year, I would examine whether the committee met its goals and what tangible evidence supports that judgment. I would also seek feedback on my leadership so that completing the plan is not the only measure of learning. These three goals extend the cycle into further equity inquiry, participation in governance, and direct leadership of collaborative implementation.`,
};

const details = {
  'A-mission': 'These responsibilities apply across the full student population.',
  A1: 'The additional tables therefore serve different purposes in the inquiry. The classroom-experience item concerns how students perceive learning, the participation item concerns their involvement beyond lessons, and the language indicator concerns reported progress. I selected each because it might clarify a different dimension of school connection. Their value depends on keeping those distinctions visible as I compare them with attendance.',
  A2: 'The source choices were deliberate. The teacher could describe instructional conditions that an attendance report cannot show, while the student could explain the meaning of a placement experience. The counselor understood the coordination of attendance and family assistance, and the parent understood community travel conditions. Comparing these perspectives helped me avoid relying on only the school office or only a classroom account.',
  A4: 'Understanding those differences is necessary when considering how support systems can be developed and maintained over time.',
  B1: 'The distinction among these factors matters for planning. Professional learning could address aspects of instruction, while a placement policy requires attention to institutional decisions. Housing and transportation concerns require coordination with services beyond a classroom. Treating them as interchangeable would obscure the different responsibilities and resources involved in responding to students.',
  B3: 'For this reason, the school needs a receptive approach at enrollment as well as continuing follow-up. A welcoming first contact can begin a relationship through which a student later feels able to describe a difficulty affecting attendance.',
  B4: 'These supports would be coordinated around students rather than offered as disconnected programs. The teacher group addresses everyday learning, the intervention addresses specific language needs, and the extended opportunities and attendance team address connection and access.',
  B5: 'The available roles are an important part of the feasibility argument. The proposal does not begin by assuming an entirely new department or staff. It asks how existing coordination, counseling, and instructional responsibilities might be aligned more deliberately. That alignment would still require agreement about workload and priorities so that responsibility for English learner support is clear and sustainable.',
  C1: 'The two proposals are intended to complement one another. An improved classroom experience cannot by itself remove a housing or transportation barrier, and a supportive mentor cannot replace appropriate language instruction. Their connection is the student experience: one strengthens access to learning during the day, while the other helps identify circumstances that interrupt participation. Coordinating these efforts would keep the problem statement visible across the different adults involved.',
  C2: 'The approach depends on coordinated follow-through. The mentor maintains contact, while the counselor helps arrange services that fall outside a mentor\'s role. This division makes the relationship more useful when the student identifies a practical need.',
  C3: 'The mission and vision therefore provide more than introductory language. They offer a basis for asking whether each proposed action delivers the kind of support the school says students should receive.',
  C4: 'The second round built on the first rather than repeat the original proposal unchanged. I presented the adjustments already made so the counselor could respond to a more developed plan. This sequence helped me see feedback as an ongoing process: one colleague identified instructional sharing and belonging, while another added practical concerns about relevance and staffing.',
  C5: 'The invitation to participate would need to remain connected with those shared purposes throughout the year. Teachers and support staff should understand how their particular contribution fits the broader response, and families and students should be able to describe their experience of it. That continuing communication can help identify problems early and keep the work from depending only on initial enthusiasm.',
  D1: 'Both colleagues also helped me connect participation with support. Teachers asked to change practice need useful resources and an opportunity to exercise judgment. Staff asked to mentor need a clear role and someone to consult. Recognizing those conditions changed how I would invite people into the work.',
  D2: 'Understanding context also requires recognizing the difference between a familiar routine and a well-supported explanation of its effects. Longstanding practices may contain useful knowledge as well as limitations. I need to ask colleagues how those practices developed, what purposes they serve, and what evidence they use to judge them. That kind of inquiry can make a proposed change more informed and can show respect for the people who have sustained the school\'s work.\n\nThe governance and committee meetings give me a setting to practice this discipline. I can listen to how members frame concerns, notice which perspectives enter the discussion, and consider how decisions are connected with student evidence. These experiences can help me develop the patience and contextual understanding that my tendency to move quickly toward solutions sometimes overlooks. They also allow me to contribute as a collaborator while learning from the leadership already present in the school.',
  D3: 'The committee work will require the same attention to participation that I practiced in this inquiry. Preparing an agenda is only the beginning; I will need to help members interpret information, consider different views, and agree on responsibilities they can carry out. Reviewing our actions after each meeting will help me connect planning with implementation and notice when the process needs adjustment. This makes the current coordination role a practical opportunity to develop leadership before moving into administration.'
};
for (const [id, text] of Object.entries(details)) {
  const paragraphs = module.exports[id].split('\n\n');
  if (paragraphs.length === 1) paragraphs[0] += ' ' + text;
  else paragraphs.splice(paragraphs.length - 1, 0, text);
  module.exports[id] = paragraphs.join('\n\n');
}
